### ISSUE TITLE
move logo art to its own repo

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1023]
This includes everything in the top-level logos directory.  I already copied the logo for the manual into the stan-reference/img directory.

**Comment by syclik** [comment]
Bob, I'll take care of this. Question: what license do we use? 
BSD? CCPL? other?

**Comment by bob-carpenter** [comment]
OK.  Do we run out of public repos at some point?

We've used CC-BY-AT for the manual, but you should
ask Michael, since he's making the logo.  Maybe we
should start a foundation and trademark it.  You
want to be the head of an institute?  I hate admin.

- Bob

**Comment by syclik** [comment]
No limit to public repos. We have a limit to number of free private repos.

@betanalpha, @malecki: logo license?

Regarding foundation, if necessary, I'll do it. I don't like admin, but I
don't hate it.

**Comment by betanalpha** [comment]
Bob, do you mean CC-BY (http://creativecommons.org/licenses/)?

I’d lean slightly towards CC-BY-NC — people using our code is fine, 
but branding their code with our logo is vaguely uncomfortable to me, 
unless someone can convince me otherwise?  That said, if CC-BY-NC
causes problems, for example with the manual license, then I’m fine
with CC-BY.

What about the font license? http://www.fonts.com/font/microsoft-corporation/corbel

**Comment by bob-carpenter** [comment]
The manual is now "CC-BY" --- I think there used to be "AT"
designations in CC v3.    Looks like they all include
attribution now --- at least CC-BY does.  

I'm totally OK with not making the logo CC-BY.  

I believe if you want serious protection, you need to apply
for a trademark, which looks like it'll cost around US$400
for the US version. 

I believe we could also copyright it and just reserve
all rights.  I have no idea what the implications would
then be for us using in the manual with the manual being
CC-BY.  

We could, of course, change the license on the manual.
No reason it has to be CC-BY.

The only thing I'm dead set against is any "academic
only" stuff.  

- Bob

**Comment by syclik** [comment]
Closed by #1402.
