### ISSUE TITLE
Header functions not defined inline | multiple definition linker errors

### ISSUE THREAD

**Issue by mcobzarenco** [stan-dev/stan#1149]
I am working on a library which uses the auto differentiation component of stan. In `src/stan/agrad` all functions seem to be defined in header files, but are not marked inline. This means they can only have 1 definition across all translation units. I.e. one can only include agrad/autodiff.hpp in only one cpp file or otherwise get a _lot_ of multiple definiton errors. E.g.

`multiple definition of stan::math::gradRegIncBeta(double&, double&, double, double, double, double, double, double, double)' `
etc. etc. etc.

It may be that I don't understand how stan is supposed to be built, but function definitions in header files not marked inline or in an anonymous namespace are a big NO-NO. Does someone know why they are not marked inline or are defined in their own cpp files? How I can use `agrad` as a separate lib if I can only include agrad/autodiff in one .cpp file?

Marius

**Comment by bgoodri** [comment]
I think I ran into this problem compiling rstanarm. If I made each .stan program into a separate .o file and then combined them together into a shared object, there were linker errors involving `log_sum_exp` IIRC. So, I just glued all the .cpp files into one .cpp file and the linker errors went away. In other words, it doesn't affect me really, but the bug is probably still there.

**Comment by syclik** [comment]
Please let me know if you see that again. Or a way to test it.

**Comment by bgoodri** [comment]
Just compile any two Stan programs.

library(rstan)
funnel <- stan_demo("funnel", chains = 0)
funnel_reparam <- stan_demo("funnel_reparam", chains = 0)

Then, in a shell, change directories to whatever

tempdir()

evaluates to and try

R CMD SHLIB --output=test *.o
