### ISSUE TITLE
Named, variable number of arguments to ODE functions?

### ISSUE THREAD

**Issue by edbaskerville** [stan-dev/stan#1164]
Currently, the time-derivative function for an ODE integrator takes a fixed number of arguments, e.g.,

```
// ...
  real[] dydt(real t, real[] y, real[] theta, real[] x_r, int[] x_i) {
    // ...
  }
// ...
  y_hat <- integrate_ode(dydt, y0, t0, ts, theta, x_r, x_i);
// ...
```

There are many cases where it makes sense to structure input data differently, e.g., a system with multiple driving time series, say, temperature, precipitation, and number of mosquitoes. It would be nice to allow the time-derivative function to have an arbitrary list of arguments at the end, of arbitrary type:

```
// ...
  real[] dydt(real t, real[] y, real[] theta, real[] temp, real[] precip, int[] mosq) {
    // ...
  }
// ...
  y_hat <- integrate_ode(dydt, y0, t0, ts, theta, temp, precip, mosq);
// ...
```

It would be even nicer if parameters (say, `alpha` and `beta`) were included in this variable-length list of arguments:

```
// ...
  real[] dydt(real t, real[] y, real alpha, real beta, real[] temp, real[] precip, int[] mosq) {
    // ...
  }
// ...
  y_hat <- integrate_ode(dydt, y0, t0, ts, alpha, beta, temp, precip, mosq);
// ...
```

but I imagine that would be substantially more work, since the fact that `dydt(t)` needs to be differentiated with respect to `alpha` and `beta` would need to be inferred from the model specification.

**Comment by bgoodri** [comment]
I think there is a more general issue here of how Stan functionals (will) handle arguments to the user-defined functions. I suggested being able to define user-defined functions in transformed data so that fixed arguments would be in scope but @bob-carpenter did not like that idea. Another option would be to declare user-defined functions as friend functions in the class definition.

**Comment by bob-carpenter** [comment]
Right.  I think having scope outside of the function itself
is confusing.  What Ben's suggesting would remove most of the
problematic issues with the containing environment changing
after the function definition.  And it could be coded by turning
our functions into member functions rather than standalone statics
as they are now.  So they wouldn't be accessible without a class
instantiated.

**Comment by bgoodri** [comment]
But we need to not break expose_stan_functions() in rstan.

**Comment by bgoodri** [comment]
I started a wiki page for this
https://github.com/stan-dev/stan/wiki/Functionals-spec

**Comment by bgoodri** [comment]
Upon further review, I am switching my vote to member functions.

**Comment by bob-carpenter** [comment]
This is rolled into other issues---we're not going to add named arguments any time soon and if we did, it wouldn't just be for ODEs.
