### ISSUE TITLE
Separate math/ode from math

### ISSUE THREAD

**Issue by jpritikin** [stan-dev/stan#1192]
For models where ODE is not required, it would be nice to avoid including all the ODE support headers on the inclusion of src/stan/math.hpp. In other words, I suggest that we relocate

    #include <stan/math/ode.hpp>

This change is worth about 110k lines of headers (600 header files).

**Comment by syclik** [comment]
Josh, can you edit your issue on GitHub? It's missing the include. (You'll
see when you get there.)

I'll remove this comment after you fix it.

**Comment by bob-carpenter** [comment]
I should've put this here rather than the previous issue.

`math.hpp` already depends on Boost and Eigen.   

`ode.hpp` only depends on Boost, but there are certainly lots of headers there.   Boost libs tend to include a lot of other Boost libs.  Soon, `ode.hpp` will depend on other libs.

We have an ongoing issue to only include what we use in each header file, #811, and we should fix that one first.  I'm about to fix the math includes issue, #778, for the next release.

When those are fixed, `math.hpp` will only be a handful of includes and it'll be easy to pick and choose the ones you want without a sprawling, hard-to-maintain custom include file.

**Comment by syclik** [comment]
@jpritikin, instead:
```
#include <stan/math.hpp>
```

Try including:
```
#include <stan/math/functions.hpp>
#include <stan/math/matrix.hpp>
```

As Bob's mentioned, we're trying to include only what's necessary in the header files, but things like `math.hpp` are going to include everything under it.

One thing we might consider is moving our `ode` solving capability out of `math`, but I don't think that's what we'll do for now. If that's enough of an answer for now, mind closing the issue?

**Comment by jpritikin** [comment]
Alright, that works. FYI, I needed:

    #include <stan/prob/constants.hpp>
    #include <stan/prob/traits.hpp>
    #include <stan/error_handling.hpp>

**Comment by syclik** [comment]
Hi Josh,

What does that mean? You shouldn't need to include additional headers just
for the math, unless you're trying to use the autodiff library. If you
needed to include those in addition to the math headers, that's definitely
an issue that we should track down.


Daniel

**Comment by jpritikin** [comment]
Yeah, I'm using autodiff. That must be it.

**Comment by syclik** [comment]
Try including stan/agrad.hpp or stan/agrad/rev.hpp before including any of
the Stan math functions. This *should* bring in the math functions in the
correct order.

**Comment by bob-carpenter** [comment]
Are there known order dependencies?  If so, we should open another
issue and try to get rid of them.

- Bob

**Comment by syclik** [comment]
The only order dependency I know of is by design: the agrad headers need to
be included before the math headers. This will define the template
specializations for agrad in the correct order. If agrad is not included,
then the math functions should define and declare everything properly.

If Joshua has touched on order dependencies that I didn't know about, I
agree that we need to open a separate issue to remove them.

**Comment by bob-carpenter** [comment]
Any idea why they need to be included first?  Won't each
agrad header bring in the math header it needs?

- Bob

**Comment by syclik** [comment]
Yes, but not all our autodiffable functions are template specialized for
stan::agrad::var, so they're not included when including something like
stan/agrad/rev.hpp.

For example, we don't have a template specialization for stan::agrad::var
for stan/math/functions/lbeta.hpp. By including only stan/agrad/rev.hpp, we
won't get a definition for stan::math::lbeta, but by first including
stan/agrad/rev.hpp, then including stan/agrad/math/functions.hpp, we can
now use the templated version of stan::math::lbeta for stan::agrad::rev.

**Comment by jpritikin** [comment]
I don't really follow this discussion, but here are the headers and 
order that I am using:

#include <stdexcept>
#include <utility>
#include <vector>
#include <stan/agrad/rev.hpp>
#include <stan/agrad/rev/matrix.hpp>
#include <stan/math/functions.hpp>
#include <stan/math/matrix.hpp>
#include <stan/math/rep_array.hpp>
#include <stan/math/rep_vector.hpp>
#include <stan/math/rep_row_vector.hpp>
#include <stan/math/rep_matrix.hpp>
#include <stan/prob/constants.hpp>
#include <stan/prob/traits.hpp>
#include <stan/error_handling.hpp>
#include <stan/version.hpp>
#include <stan/model/util.hpp>
#include <stan/agrad/fwd.hpp>
#include <stan/agrad/fwd/matrix.hpp>

-- 
Joshua N. Pritikin
Department of Psychology
University of Virginia
485 McCormick Rd, Gilmer Hall Room 102
Charlottesville, VA 22904
http://people.virginia.edu/~jnp3bc

**Comment by syclik** [comment]
Ok. You've just confirmed there's no *new* include order issue.

You'll want to move the includes for stan/agrad/fwd.hpp and
stan/agrad/fwd.hpp to right after the include for stan/agrad/rev/matrix.hpp.

**Comment by bob-carpenter** [comment]
Can we create an issue to try to resolve this order dependence?

  agrad/rev/matrix.hpp  <  agrad/fwd.hpp

You repeated stan/agrad/fwd.hpp --- was there another order dependency?

And is the "right after" critical?

- Bob
