### ISSUE TITLE
bad_alloc exception with vectors of negative size

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1194]
I expected the model below to provide an error message from Stan. Instead, it throws a `std::bad_alloc` exception.

```
parameters {
  vector[-1] theta;
}
model {
}
```

Output from CmdStan:

```
> ./issue-685 sample

Exception: std::bad_alloc
Diagnostic information: 
Dynamic exception type: St9bad_alloc
std::exception::what: std::bad_alloc
```

**Comment by syclik** [comment]
The error also occurs for this model:
```
parameters {
  real theta[-1];
}
model {
}
```

**Comment by bob-carpenter** [comment]
Nice test.  I'm amazed this hasn't come up before.

The code generator will produce something like:

```
std::vector<var> theta(-1);
```

Then the fun starts, because the constructor for `std::vector`
takes a `size_t` (unsigned) type, so the -1 gets statically
cast to some huge unsigned value, which is too big to allocate,
hence the bad allocation exception.

This isn't something we can catch statically because the range
can be data, but we could change code generation to produce something 
like:

```
std::vector<var> theta;
stan::math::resize(theta,-1);
```

where using our own resize method would allow an `int` argument
and hence allow the error to be caught with a reasonable message.

We'd need to do the same for matrices and vectors.

It'll add some processing overhead, but give the most coherent message.

**Comment by syclik** [comment]
Is it worth the overhead? I realized that we couldn't do it statically, but
I wasn't thinking about how the generated code looks.

I'm really surprised it hasn't come up before.

**Comment by bob-carpenter** [comment]
This is a serious issue that still stands (we don't want to crash our containing environment!), so I'm upping milestone.

The fix is to add checks that all these numbers are positive before letting the allocations get called, so either @mitzimorris or I could do it.

**Comment by bob-carpenter** [comment]
I think the best we can do is write a function like this one and apply it to all index sizes:

```
inline int non_negative_container_size(int n) {
  if unlikely(n < 0) {
    std::stringstream ss;
    ss << "ERROR: require non-negative size for container, found size=" << n << std::endl;
    std::string msg = ss.str();
    throw std::length_error(msg);
  }
  return n;
}
```

**Comment by mitzimorris** [comment]
this goes into the generated code?

**Comment by bob-carpenter** [comment]
Yes, instead of generating

`std::vector<...> x(foo)`

you'd generate

`std::vector<...> x(non_negative_container_size(foo))`

and it'd be great if you could come up with a shorter name that's a bit more descriptive.  `return_if_non_neg` maybe or `err_if_neg`

The point is that calling an inline function with the unlikely branch on an integer test shouldn't add much overhead.

**Comment by bob-carpenter** [comment]
And `foo` is the size here, so there may be other calls.

**Comment by mitzimorris** [comment]
investigating this behavior.  depending upon the context, there are some runtime checks which detect negative vector sizes and throw an error accordingly.

in a data block, the following variable declaration:

```
  int d;
  vector[d] d_v;
```

when run with data file that contains  `d <- -1`, will generate a runtime error:

```

Exception: Found negative dimension size in variable declaration; variable=d_v; dimension size expression=d; expression value=-1
Diagnostic information: 
Dynamic exception type: std::invalid_argument
std::exception::what: Found negative dimension size in variable declaration; variable=d_v; dimension size expression=d; expression value=-1

```

this is because generated code contains:

```
      validate_non_negative_index("d_v", "d", d);
      d_v = vector_d(static_cast<Eigen::VectorXd::Index>(d));
```

so dimension gets checked before variable declaration.
function from file:
stan_math/stan/math/prim/mat/err/validate_non_negative_index.hpp




checks for variables in data and transformed data blocks, but not in param, transformed param, and model blocks.

**Comment by bob-carpenter** [comment]
What do you mean that it doesn't check in param, transformed param or model blocks?  If PR #2200 doesn't fix that, would you mind opening a new issue for those environments.  Thanks.

**Comment by mitzimorris** [comment]
This was fixed in #PR2200.  The generated code for all container variable initializations is always preceeded by a test to check the declared dimension.  This must be runtime, as dimensions can be variables.  Therefore, the stan code:

```
data {
  int N;
}
transformed data {
  vector[N] v1;
}
```
is translated to:

```
        validate_non_negative_index("v1", "N", N);
        v1 = vector_d(static_cast<Eigen::VectorXd::Index>(N));
        stan::math::fill(v1,DUMMY_VAR__);
```

at runtime program will fail gracefully with an error message.

```
Found negative dimension size in variable declaration; variable=v1; dimension size expression=N; expression value=-1
```
