### ISSUE TITLE
negative binomial with direct variance or std-dev parameterization

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1310]
Given how people are using negative binomial, I think it would be nice to have some more convenient parameterizations that don't require users to solve a bunch of equations and then encode them in the Stan program.  It would make sense to me to use either a

* mean and variance parameterization
* mean and standard deviation parameterization

It seems most natural to put this on the positive scale rather than the log scale, but I'm not an expert in using these models, and it seems like it'd be nice to have a negative binomial with the mean on a log scale for GLMs.

The negative binomial is exhausting!

**Comment by aadler** [comment]
The exhaustion comes from two main sources, I believe. Firstly, which is the random variable and which is the fixed value - the failures or success (just follow five years worth of arguments on Wikipedia about this). Andrew uses one way, De Groot the other (IIRC). Another issue I've come across with the negative binomial is that the relationship between mean and variance can be looked at on both a linear and quadratic basis. For example, see [Ismail & Jemain (2007)](http://www.casualtyactuarialsociety.com/pubs/forum/07wforum/07w109.pdf) and [Ver Hoef & Boving (2007)](http://digitalcommons.unl.edu/usdeptcommercepub/142), although the "linear" versions act that way by ignoring the components that may make up the mean.

To wit, the parametrization I find most convenient and use most often defines the negative binomial as the distribution of the random variable k where k is the number of (random) failures before a fixed number r successes, then

p_k = &Gamma;(r + k) / (&Gamma;(r)&Gamma;(k + 1) &beta;^k (1 + &beta;)^(r + k)

In this version:
- both r and &beta; > 0
- Mean = r&beta;
- Variance = r&beta;(1+&beta;)  = r&beta; + r&beta;² (so V2M = 1+&beta;)
- r is the shape and &beta; is the **scale** of the mixing gamma for the Poisson
- canonic p (probability of success) = 1/(1+&beta;)
- canonic q (probability of success) = &beta;/(1+&beta;)
- &beta; is the ratio of failure to success (q / p)

In the above parametrization, if you look at &beta; as &mu;/ r, you get the quadratic version:

Var = &mu;+ &mu;² / r

If you "ignore" the fact that &mu; is composed of &beta; you get the linear version:

Var = &mu;+ &beta;&mu;

So, if you are going to try and build a Mean/Var paramterization, are you going to use the linear or quadratic relationship? Which is why I like using the "building blocks" approach.

**Comment by bob-carpenter** [comment]
I was just suggesting using a direct parameterization:

  y ~ neg_binomial_mean_scale(mu,sigma);

where mu is mean and sigma is scale (sqrt variance).  Then the user
could do whatever they want, for instance, such as

  neg_binomial_mean_scale(mu, sqrt(mu + mu^2 + r));

I know it's not standard, but it still seems easier than assuming
a fixed form and having people to do algebra to get the std-dev
they want.

Why would you use a model where the variance rather than std-dev
is linearly related to the mean?  

- Bob

**Comment by aadler** [comment]
I think Ismail & Jemain do so for calculation reasons.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#78
