### ISSUE TITLE
rev: fmax and fmin look like they're not manging memory properly.

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1311]
Check the implementation.

**Comment by bob-carpenter** [comment]
Could you be a bit more sepcific about what's going on?  Is it leaking?

Andrew wanted to move to just using max() and min(), which I think makes sense for our users.  So feel free to deprecate fmax() and fmin() while you're at it.

 At the expense of repeating myself for the gazillionth time, the main problem is signatures, where we'd have:

```
max(real,real):real
max(int,real):real
max(real,int):real
max(int,int):int
```

The only thing we lose is `fmax(int,int):real`, but we don't need it because Stan will promote int to real.

I don't know if we'll be able to change implementations since we're just using the built ins as far as I can tell.

**Comment by syclik** [comment]
I just dropped the issue in to keep track of it after this refactoring, but
I'm not sure where the memory is going without a new call:

`return var(precomputed_gradients(stan::math::NOT_A_NUMBER, vars, grads));`

I don't know if there's an implicit new in there or if it gets created
properly somehow, but it's different from the other instances of creating a
vari.

**Comment by bob-carpenter** [comment]
I don't think there's a memory issue as is.    

The return in `agrad/rev/functions/fmax.hpp`

```
return var(precomputed_gradients(stan::math::NOT_A_NUMBER, vars, grads));
```

is calling this function defined in agrad/rev/internal/precomputed_gradients.hpp, not a constructor:

```
var precomputed_gradients(const double value,
                           const std::vector<var>& operands,
                           const std::vector<double>& gradients) {
   return var(new precomputed_gradients_vari(value, operands, gradients));
}
```

I see a bunch of problems with how it's implemented, including

* [ ] the ugly `if(` syntax without a space,
* [ ] use of `boost::math::isnan`, which I though we were getting rid of in favor of our own `isnan` applied directly to a `var` (don't fish into classes unless necesary),
* [ ] a redundant (and inefficient) copy constructor call in the return,
* [ ] redundant implementations of comparisons (no reason to use `a.vi_->val_ > b.vi_->val_ ? a : b;` when we could use `a > b ? a : b` instead as long as we bring in the `var` comparison operator, and 
* [ ] a general vector-based precomputed gradients when we should be using `precomp_vv_vari` instead.

The second should be using our own straightup `isnan` function without any `b.vi_->val_` fiddling inside of `fmax.hpp`.  

* [ ] same again for `fmin`
