### ISSUE TITLE
manual: effective sample size

### ISSUE THREAD

**Issue by fredRos** [stan-dev/stan#1334]
Hey stan developers,

after a private conversation with Michael Betancourt, he encouraged me to post some comments on the manual section on *Effective Sample Size* as issues here:

* [x] Some references would be nice, there is not a single one
* [x] in the variogram formula V_t = ..., I guess the 2nd denominator should be (N_m - t) instead of N_m (spotted by @greenwald)
* [x] in *only the initial estimates of ρˆt where ρˆt < 0 will be used* it should say *ρˆ t>0*

As to the last point, Michael mentioned that most of the time you just see positive correlations. So the paragraph that explains that you stop if you encounter anticorrelation is a bit misleading. I suppose you stop at some fixed lag, else you might go to infinite lag if the correlation is always positive.

* [x] Finally, a hint on how you numerically compute the correlation times (http://www.mcmchandbook.net/HandbookChapter1.pdf and Eigen's FFT according to Michael) would help.

**Comment by andrewgelman** [comment]
Hi, I’m pretty sure the covariances can’t stay positive for all lags, given the finiteness of the data that are being used.
A

**Comment by betanalpha** [comment]
Geyer covers this pretty well.  Exact autocorrelations can happen only on
odd lags — if you sum over pairs then the paired autocorrelation is
guaranteed to be positive modulo estimator noise.  This is the motivation
behind his many termination criterion.  We currently do not do the paired
expectations but we also don’t expect to be in the negative autocorrelation
regime (NUTS almost by construct avoids that) so terminating at the first
negative autocorrelation is a pretty reasonable approximation for stopping
when the noise in the autocorrelation estimator dominates.

**Comment by bob-carpenter** [comment]
These will be addressed in the pull request for the manual update for issue #1202 for version 2.6.2 of the manual

**Comment by mariadzul-usgs** [comment]
Hello, 
On a similar note, I was wondering if the N_eff equation on page 375 (Stan Manual version 2.17.0) is correct.  Instead of having the 1/2 out front, should the denominator be (1+2*sum(rho)).  This is more consistent with N_eff equation on the previous page (p 374), and it seems to give me n_eff estimates that are more similar to those outputted by Stan.

Thanks!

Maria

**Comment by avehtari** [comment]
Hi @mariadzul-usgs, you are correct. This part has been fixed in version 2.18 (fix already merged). 2.18 will also have better estimate in the code. 

This issue was closed almost 3 years ago. Next time you find something to fix in manual, it's better to comment in an open issue for the next manual. For 2.18 the appropriate issue #2437
