### ISSUE TITLE
normal_cdf_log underflow

### ISSUE THREAD

**Issue by rubind** [stan-dev/stan#1424]
Hi,

I noticed an underflow with normal_cdf_log using PyStan 2.6.3.0 with python 2.7.9 (under OS X Yosemite) and python 2.7.7 (under Scientific Linux SL release 5.5):
normal_cdf_log(0., 40, 1.) returns -inf

Please let me know if you're seeing something similar on your installations.

Thanks,
David

**Comment by syclik** [comment]
Hi David,

What are you expecting it to evaluate to? That's evaluating the normal cdf
at 0 with a mean of 40 and standard deviation of 1.

It seems reasonable that at 40 standard deviations lower than the mean this
gets evaluated as log(0).

Daniel

**Comment by jgabry** [comment]
If the difference between 0 and normal_cdf(0, 40, 1) is of any meaning at
all it's entirely abstract (theoretical), so I agree with Daniel that
this should be evaluated as log(0).

**Comment by bob-carpenter** [comment]
Here's what R does:

  > pnorm(0, 40, 1, log.p=TRUE)
  [1] -804.6084

So it's not even close to overflowing to -infinity on the log scale. 

Stan's log CDF functions just naively apply

  log(foo_cdf(y, theta)) 

and exp(-800) underflows to 0 in the double-precision floating point
arithmetic we use.

Ideally, Stan would follow R in using specialized algorithms designed 
to prevent under and overflow on the log scale.

The reason we haven't been too worried about this is twofold.  First, the
one Daniel and Jonah mentioned --- if there's a model where this is a problem, 
then there are bigger  problems with the model than overflow/underflow of cdfs 
on the log scale.

Second, all Stan's algorithms run with derivatives, and when you take the derivative

  d/dy log(normal_cdf(y,mu,sigma))

  = (1 / normal_cdf(y,mu,sigma))
    * d/dy normal_cdf(y,mu,sigma)

you reintroduce an overflow problem because the first term's going to
overflow and the second term's going to be near 1 because the CDF is
very flat out in the tails.

- Bob

**Comment by rubind** [comment]
Hi All,

I’ve run into the underflow issue with the exp_mod_normal distribution. If I let tau = 1/lambda, then tau -> 0 recovers a normal distribution. For example, a call to exp_mod_normal_log(2., 0., 1., 100.), corresponding to a distribution that is very nearly normal, gives -inf instead of -2.868. I’m already adding an “if” statement for tau < 0 (giving an easy one-parameter way of adding positive or negative skewness), so adding an "if" statement for tau ~ 0 isn’t really a problem.

It’s interesting that R handles it differently.

Thanks for the fast reply, and thanks for such a great tool!

-David

**Comment by bob-carpenter** [comment]
You really want to bound your model away from bad boundary behavior
using priors and/or constraints on the parameter declarations.

For example, the exp_mod_normal requires lambda > 0, which will force
1/lambda > 0 (in theory, it'll be >=0 in practice due to potential
underflows).  So if lambda is a parameter, you want to declare:

  real<lower=0> lambda;

And if there's a problem when lambda gets really big and thus
1/lambda gets very small, you want a prior on lambda to keep
its values reasonable.  One way to do that, which we don't recommend,
is to include an upper bound on lambda, too.

- Bob

**Comment by syclik** [comment]
@rubind, if you think normal_cdf_log is ok, please close this issue and open one for exp_mod_normal.

**Comment by bob-carpenter** [comment]
I'm moving this to our longer-term to-do list because it's not just `normal_cdf_log`, it's all the log-scale CDFs, CCDFs, and truncation statements.

**Comment by syclik** [comment]
Thanks, Bob.

@rubind, thanks for bring this issue up.

Closed #1424 <https://github.com/stan-dev/stan/issues/1424>.

—
Reply to this email directly or view it on GitHub
<https://github.com/stan-dev/stan/issues/1424#event-280445101>.
