### ISSUE TITLE
Next Manual, 2.7.0 (revisited)

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1508]
This is the issue for the next manual.  All manual-related requests and patches should go here.  There will be a branch named after the issue as soon as someone creates one that can also be modified directly if you have push permission on stan-dev.

**Comment by bob-carpenter** [comment]
From @jonathan-g in #1507:

The 2.6.2 manual (Saturday 14th March, 2015) describes Phi on page 46 as $\int_{-\infty}^x \text{Normal}(y|0,1) dy$, but on page 312 as $\frac{1}{\sqrt{2\pi}} \int_0^x e^{-t^2/2} dt$.  These are inconsistent in the lower limit of integration. I think the definition on page 312 should have $-\infty$ as the lower limit.

**Comment by randommm** [comment]
In chapter 11. Latent Discrete Parameters:

* [ ] In subsubsection Marginalizing out the Discrete Parameter, after the sentence "Stan operates on the log scale and thus requires the log likelihood":

`log_sum_exp` should be over `log Uniform(s|1, T ) + t=1 log Poisson(D t |t < s ? e : l)` (it's missing bracket). So it would be: 
`log_sum_exp ( log Uniform(s|1, T ) + t=1 log Poisson(D t |t < s ? e : l) )`


* [ ] In subsection "Discrete Sampling", the sentence

"Although not computationally advantageous compared to working in expectation using lp,
it is possible to use Stan to sample the value of s at every iteration."

Is misleading. We are sampling the discrete parameter via "working in expectation using lp", so it is the computationally advantageous way of doing it.

**Comment by bob-carpenter** [comment]
* [ ] Add acknowledgment for new logo:

<blockquote>
The Stan logo was designed by Michael Betancourt and Stephanie Mannheim (<tt>http://www.stephaniemannheim.com/</tt>).
</blockquote>

**Comment by bob-carpenter** [comment]
* [ ] close space to footnote on first page of "Execution of a Stan Program" chapter

**Comment by bgoodri** [comment]
In the subsection "Program Block: transformed parameters" and the subsection "Reject Statements" (and perhaps elsewhere) we should emphasize that inequality constraints are intended to catch programmer or numerical errors, not to define a probability model (in contrast to constraints in the parameters block). 

The issue is fundamentally the same as in
```
parameters {
  real a;
  real<lower=a> b;
  real<lower=a,upper=b> theta;
}
model {
  theta ~ normal(0,1); // wrong, needs T[a,b]
}
```
which is just as wrong as
```
parameters {
  real a;
  real<lower=a> b;
  real theta;
}
model {
  if (theta < a || theta > b) reject("theta not in (a,b)");
  theta ~ normal(0,1); // still wrong, needs T[a,b]
}
```
The conceptual issue is that the prior does not integrate to 1 over the admissible parameter space; it integrates to 1 over all real numbers and integrates to something less than 1 over (a,b). In these simple univariate cases, we can overcome that with the `T[,]` notation, which essentially divides by whatever the prior integrates to over (a,b). 

Unfortunately, users are using the inequality constraints in transformed parameters blocks and similarly `reject()` statements to enforce complicated inequalities on multivariate functions, in which case their priors integrate to something less than 1 over the region of the parameter space where the complicated inequalities are satisfied. But we don't generally know what `value` the prior integrates to, so we can't do an `increment_log_prob(-log(value))` to compensate.

It is also the same problem as doing
```
parameters {
  real<lower=0,upper=1> correlations[K * (K - 1) / 2];
}
transformed parameters {
  corr_matrix[K] Lambda; // may get rejected by check_pos_definite
  int counter;
  counter <- 1;
  for (i in 1:K) {
    Lambda[i,i] <- 1;
    for (j in (i+1):K) {
      Lambda[i,j] <- correlations[counter];
      Lambda[j,i] <- Lambda[i,j];
      counter <- counter + 1;
     }
  }
}
model {
  correlations ~ beta(alpha,beta); // wrong
  ...
}
```
In this case, the prior on the correlations integrates to 1 over the (0,1)^(K * (K - 1) / 2) hypercube but for K > 2, many points in that hypercube violate the positive definiteness constraint on correlation matrices. So, the prior integrates to some unknown number less than 1 over the positive definite subspace that we can't compensate for.

And even if this is not a "big deal" in particular models where the amount of truncated posterior density is negligible or constant, we can't sample from that truncated posterior efficiently. So, users really need to utilize 1-to-1 mappings that guarantee the constraints are satisfied and only use `reject()` statements to check themselves.

**Comment by bob-carpenter** [comment]
* [ ] add a warning in the regression chapter that estimates near boundaries will cause problems

**Comment by bob-carpenter** [comment]
* [ ] Add Robert L. Grant as core developer

* [ ] Add Sloan Foundation (?) and ONR (?) funding --- don't have grant numbers or anything for either yet

**Comment by jonathan-g** [comment]
page 451, section "Warmup Times and Estimating the Mass Matrix": minor LaTeX problem due to using non-ASCII character instead of ASCII single-quote for apostrophe in source: "... standardizing the data doesnâ ̆ Z ́ t always help. Therefore, Stan ..."

**Comment by bob-carpenter** [comment]
Did anybody have experience in implementing negbin k (negative binomial when k=1) in stan.  I was trying to implement using lmgamma function but I assume there is a typo in stan manual:

* [ ] product sign should be replaced with sum sign, 
* [ ] gamma function sign with log gamma function sign, 
* [ ] 1 - j with j - 1.

**Comment by bob-carpenter** [comment]
* [ ] move discussion of divergence, treedepth, etc., from CmdStan manual to Stan manual and leave reference behind
