### ISSUE TITLE
OpenMP and MPI for Boost ODE solver

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1511]
Sebastian Weber suggested on stan-users (and I concur) that we figure out how to turn on parallelization in the integrator.  See:

http://headmyshoulder.github.io/odeint-v2/doc/boost_numeric_odeint/tutorial/parallel_computation_with_openmp_and_mpi.html

This should be possible now that we are only calling it with `double` values.

**Comment by wds15** [comment]
Here is a very interesting article:

http://arxiv.org/abs/1212.6326

describing the use of openCL/openMP/CUDA in an easy way with odeint. Reading through it quickly they say the GPU story buys you around 10-20x fold increase in speed if the problem is large (not sure what larger refers to). Otherwise the use of Thrust with openMP enabled gives good performance according to the paper, but have a read.

**Comment by bob-carpenter** [comment]
That sounds in line with what other shave told me about
GPU speedups.

I just watched Chiyuan Zhang (@pluskid) demo a deep belief net 
in Julia's Mocha.jl (a really sweet looking package, by the way)
that went about twice as fast on the GPU on a Macbook and about
20 times as fast on a server with a real GPU.

- Bob

**Comment by pluskid** [comment]
Yes GPU could be really fast if the problem is big (and yet not so big that it could fit in the GPU memory) and if the algorithm is parallelizable. The network for MNIST I showed in the demo was actually quite small comparing with most of the big networks being used in more complicated computer vision and speech recognition tasks.

I think the benchmarks for cuBLAS ( https://developer.nvidia.com/cuBLAS ) is also a good example to get a sense of speed up when switching from CPU to GPU. In my understanding, matrix multiplications (GEMMs) are not so easily parallelizable algorithms.

**Comment by syclik** [comment]
This issue was moved to stan-dev/math#101
