### ISSUE TITLE
have sampling statements in the manual index include trailing arguments

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#1564]
From a previous email exchange of mine with Bob:

> Is there a way to make the stan-reference.idx file include its arguments instead of just
>
> \indexentry{{\tt  \bfseries  poisson }!sampling statement|hyperpage}{347}
>
> Easy, but a fair bit of work.
> Just need to change the macro and then all the calls
> to it in the reference section of the manual, which don't
> have that info in their calls right now.
>
> In the index, I think it'd make sense to see just the
> parameter args, e.g., normal(reals,reals) --- skips
> the first argument.

Agreed that we can omit the left-hand side. The RStudio guys are investigating code completion for Stan programs, so we need `make manual` to produce a better index so that doc/stan-functions*.txt is exhaustive and can be used for code completion.

**Comment by bob-carpenter** [comment]
I can go through and do this.  Would it be easier to just write out a separate index file that's intended to be processed by your script and omits all the formatting and ordering stuff?

**Comment by bgoodri** [comment]
On Thu, Jul 23, 2015 at 3:20 PM, Bob Carpenter <notifications@github.com>
wrote:

> I can go through and do this. Would it be easier to just write out a
> separate index file that's intended to be processed by your script and
> omits all the formatting and ordering stuff?
>

Quite possibly.

**Comment by bgoodri** [comment]
We really need the sampling statements to have the arguments listed in the index for the next Stan so that RStudio can handle them in its next version. See https://github.com/rstudio/rstudio/pull/324#issuecomment-124774923

**Comment by bob-carpenter** [comment]
What will you do with "reals", that I've used all over the place as a stand in for int, double, double[], vector, and row_vector?  Can the code on the RStudio side cope?

**Comment by bgoodri** [comment]
I'm not sure whether it can even tell which object(s) in scope are which
types. It does for plain C++ code via libclang. That seems to be the hard
part, but if it can somehow do that, then I guess it could be taught that
reals is basically a type union.

**Comment by bob-carpenter** [comment]
Would it be easier to have RStudio work from our syntactic convention that anything ending in `_log` can be used with its first arg in a sampling statement?  Except for 

* `X_cdf_log` and `X_ccdf_log`
* `multiply_log` and `binomial_coefficient_log`

The exceptions are laid out in `stan/lang/grammars/statement_grammar_def.hpp` in the `validate_sample` functor.

**Comment by bgoodri** [comment]
We'll see. I could just add a column to the right edge of that data.frame
that is 1 if the thing is a sampling statement and 0 otherwise, and RStudio
can read that.

**Comment by bob-carpenter** [comment]
Or I could write a simple C++ program that read what was declared in Stan and have it list them all out explicitly.  Now that I type it, that seems like the obvious and easiest way to do it.  This should be pretty quick.  I'll code it up as a unit test because I know how to build it that way.

**Comment by bob-carpenter** [comment]
OK --- I just went ahead and wrote a C++ program to print everything out.
It's on this branch:

```
feature/issue-1564-manual-sampling-args
```

and to run it I did this:

```
~/stan(feature/issue-1564-manual-sampling-args)$ ./runTests.py -j4 src/test/unit/lang/write_signatures_test.cpp 
```

It prints two files:

* `function_sigs.csv`
* `sampling_sigs.csv`

for function signatures and sampling statement signatures.  Here's what they look like:

```
~/stan(feature/issue-1564-manual-sampling-args)$ head sampling_sigs.csv 
bernoulli_log,int,real
bernoulli_log,int,real[]
bernoulli_log,int,vector
bernoulli_log,int,row vector
bernoulli_log,int[],real
bernoulli_log,int[],real[]
bernoulli_log,int[],vector
bernoulli_log,int[],row vector
bernoulli_logit_log,int,real
bernoulli_logit_log,int,real[]
```

```
~/stan(feature/issue-1564-manual-sampling-args)$ head function_sigs.csv 
Phi,real
Phi_approx,real
abs,real
abs,int
acos,real
acosh,real
add,int,int
add,real,real
add,vector,vector
add,row vector,row vector
```

It'll be easy to change this program to do whatever.  I could just print out 0
or something in each argument place and collapse them all if you don't need the
type info.

What's not so easy to do is replace all of this with reals, etc.  So someting
like normal will have a gazillion entries.  Oh well, it was easy to write
if you can't use this and we have to hack through the manual.  I don't like
doing it through the manual because there can be errors.  This will match what
the code's actually doing.

- Bob

**Comment by bgoodri** [comment]
This is better in a lot of respects, but we're losing the information on
the return type, argument names, and the page number where the function is
defined in the manual. Do you think we could start with this and do some
pattern matching to the index to recover the rest?

**Comment by bgoodri** [comment]
Should probably write the .csv files to the test/ directory though

**Comment by bob-carpenter** [comment]
I didn't spend any time thinking about how to configure
until I thought we could use it.

I really don't like these ad hoc matching things.  They are
never ever maintainable.

Return type is easy.  Argument names aren't available since
they aren't part of the signature.  

The only way to get argument names is through the manual.
So if we need that, let's just go with the manual approach
and scrap this branch.

I'm still not sure exactly what you want output.   But I'm sure
if I can understand that, it'll be no big deal to produce.

- Bob

**Comment by bgoodri** [comment]
If you do make manual and look at doc/stan-functions*.txt, it is pretty
good (although it is a sequence of hacks to produce and perpetuates any
errors in the .idx file). With that information (which gets made into an
internal but readable data.frame in rstan), RStudio could do some really
cool stuff like it does with R code in terms of tab-completion, argument
lists, etc. But the big thing that is lacking is the arguments for sampling
statements, like

 bernoulli_logit;~;real;347

Since sampling statements are used so much, we really need those index
entries to be part of what RStudio offers. I could hack the _log logic onto
it, I guess but we should probably make the index entries of the sampling
statements in the user manual more useful anyway.

**Comment by jrnold** [comment]
Identifying the distributions just using `_log` with some exceptions is how I use it in the various tools.

This might give you a better sense of what might be useful for various Stan tools.
My current workflow with the `stan-mode` and `pygments` is to take the file `stan-functions.txt`, run it through a python script to parse that csv file and combine it with some other info to generate a json file [stan_lang.json](https://github.com/stan-dev/stan-mode/blob/master/stan-lang/stan_lang.json). E.g. here is an example of an entry for a function:
```json
    "normal_cdf": {
      "reals,reals,reals": {
        "argnames": [
          "y",
          "mu",
          "sigma"
        ],
        "argtypes": [
          "reals",
          "reals",
          "reals"
        ],
        "name": "normal_cdf",
        "return": "real"
      }
    },
```
I use that to generate keyword lists for `stan-mode`, and the snippets in `stan-snippets`, and the lists of keywords in the `pygments` lexer. And even this is a little less information than, I'd like. My old workflow was taking the manual pdf; using the pdf2text to generate a text file, and then parsing that to extract the signatures. Since the pdf->text was not as reliable as I'd like, it still required a bunch of manual editing. However, with that I was able to include short descriptions for each function. A few times I took a stab at using a LaTeX parser, but that never ended well.

For the purposes of autocompleting, I think that the names of the arguments are in most cases more useful than the signature types. E.g. if I am writing `student_t`, what I really want to remember is whether the degrees of freedom goes 1st or last. And if there is some sort of real time error checking, it will catch those sort of signature discrepancies. In creating the [stan-snippets](https://github.com/stan-dev/stan-mode/blob/master/stan-snippets/create_snippets.py) snippets for each function, I go through and remove any duplicates of signatures with the same set of names and only show the names in the snippets.

**Comment by bgoodri** [comment]
I put the logic for dealing with sampling statements into rstan/tools/stan-functions.R so it is less urgent to deal with them in Stan, but it would still be good to have their arguments in the index.

**Comment by bob-carpenter** [comment]
The reason I'd been reluctant to do that before is that I didn't know
how to print them.  So should normal be rendered as:

  reals y ~ normal(reals mu, reals sigma)

in the manual?  Withe slant font for y, mu, and sigma, bold for
normal, and ordinary for reals?

- Bob

**Comment by bgoodri** [comment]
That sounds good.

**Comment by bob-carpenter** [comment]
Moved to longer-term manual issues:  

https://github.com/stan-dev/stan/issues/1238#issuecomment-131242525
