### ISSUE TITLE
what's wrong with my rstan code?

### ISSUE THREAD

**Issue by reldkarl** [stan-dev/stan#1566]
try a lot of times and just can't fix it. Thank you very much if someone can helo me with it.

model1<-"data {
int nrow;
int ncol;
vector[nrow] y[ncol];
}

parameters {
real<lower=0> sigmasq1;
real<lower=0> sigmasq2;
vector[nrow] mu;
real<lower=0,upper=1> phi11;
real<lower=0,upper=1> phi22;
matrix<lower=0,upper=1>[nrow,ncol] eta;
}

transformed parameters {
matrix[nrow,ncol] h;
matrix[nrow,ncol] omega;
vector[nrow] sigmasq;
real phi111;
real phi221;
matrix[nrow,2] phi;
phi111<- 2*phi11-1;
phi221<- 2*phi22-1;
phi[1,1]<-phi111;
phi[2,2]<-phi221;
phi[1,2]<-0;
phi[2,1]<-0;
h[1,1]<- mu[1];
h[2,1]<- mu[2];
for (j in 2:ncol) {
for (i in 1:nrow) {
col(h,j) <- mu+phi*(col(h,j-1)-mu)+col(eta,j-1);
}
}
for (i in 1:ncol) {
for (j in 1:nrow) {
omega[j,i]<- exp((0.5)*h[j,i]);
}
}
sigmasq[1]<-sigmasq1;
sigmasq[2]<-sigmasq2;
}

model {
mu[1]~normal(0,25);
mu[2]~normal(0,25);
phi11~beta(20,1.5);
phi22~beta(20,1.5);
sigmasq1~inv_gamma(2.5,0.025);
sigmasq2~inv_gamma(2.5,0.025);
for (i in 1:ncol) {
eta[i]~multi_normal(rep_vector(0,2),diag_matrix(sigmasq));
y[i]~multi_normal(rep_vector(0,2),diag_matrix(transpose(omega[i])));
}
}

**Comment by bob-carpenter** [comment]
The issues are for feature requests or bug reports.  This is a problem with your code.  I'll answer here, then close the issue.

1.  exp((0.5)h[j,i]);  isn't well formed --- you need a * sign to multiply.

2.  2phi11-1; isn't well formed.  I don't know what your intent is here, but it's
not an identifier (name of a variable) or a function.  was that supposed to be `2 * phi[1,1] - 1`?

3.  For efficiency, you never want to do `y ~ multi_normal(mu, diag_matrix(sigma_sq));`  Instead, you want just the vectorized univariate normal, which works on the standard-deviation scale rather than variance scale, so that'd be `y ~ normal(mu, sigma)` with no squaring of `sigma`.

4.  You really want to vectorize all your sampling statements.

5.  Vectors are indexed row first, so I think you're transposing.

Overally, it might help if you work your way through some simpler programs and examples of how indexing and arithmetic works before trying to write something this complicated.
