### ISSUE TITLE
expressions render in user-facing syntax

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1582]
There are still some cases that aren't working properly.
- [ ] indexing

**Comment by VMatthijs** [comment]
Could you clarify this issue a bit more?

**Comment by bob-carpenter** [comment]
We got better at this but right no we can have errors in "a * b" that get translated as "multiply(a, b)" in the error messages, even though the user never wrote "multiply".  This is an issue with any kind of intermediate form normalization (* being replaced with multiply here)---we need a path back to the actual user input.

**Comment by VMatthijs** [comment]
Ah right. This has been fixed in stanc3, then. It comes with a pretty printer to render an AST as Stan syntax. (Can be used for auto-formatting.) The error messages thrown by the compiler render AST nodes using this pretty printer whenever they need to refer to a node in the error. In particular, operators get rendered properly.

**Comment by rok-cesnovar** [comment]
Fixed in stanc3 as Matthijs mentioned above.
