### ISSUE TITLE
Don't allow arrays to be accidentally instantiated with size zero

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#1609]
At the moment code like

```
transformed data {
     int N;
     real x[N];
...
```

will compile, even though `N` has not yet been given a value.  Instead `N` is given a default value of `0` on construction and then`x` becomes an array of size `0`.  This causes confusing out-of-range errors when the program later attempts to access `x`.

Either the compiler should check that `N` has been defined, or not allow arrays to be instantiated with size zero at all (given that our array dimensions are static the latter is not a bad idea).

**Comment by bob-carpenter** [comment]
I agree it's confusing.

I don't think we want to eliminate size-zero arrays, because
they're important for empty data sets, groups, etc.

The compiler doesn't have an easy way in general to check that
N is defined before accessing --- it's an undecidable problem
in general to tell if a given statement is executed before another
one, so there's no general solution forthcoming, either :-)

How about the following heuristic:  don't allow transformed data
variables to be used in the declaration of transformed data variables.
That should clean up the issue.  

We would also want to do this for generated quantities.

**Comment by betanalpha** [comment]
What about the model block?

**Comment by syclik** [comment]
I, too, think it's confusing, but I don't want to eliminate it. Arrays with 0 size are useful in checking for priors and overall Stan program behavior.

I think the heuristic might be good enough for now.

For the model block, all bets are off? We'd have to see if a local variable (at some scope... it could be declared in a larger scope than the current variable) is used in a declaration of a variable.

As an alternative suggestion, what about not allowing variables declared in the same scope used in the declaration of variables within the same scope, except in data? This rule goes away once we allow compound declaration / definition statements.

**Comment by bob-carpenter** [comment]
Agreed --- don't see how we could test in the model block.
What would we disallow?  

I think Daniel's alternative is what I was trying to propose.
You're right that it's messy w.r.t. compound declaration and 
definitions.  Partly I wanted to keep these two things cleanly
separated, which is why I haven't rushed out and implemented
compound declarations and definitions (but I should).

- Bob

**Comment by betanalpha** [comment]
The other alternative is to tweak the access error a bit —
if the size is zero then instead of reporting the using
out of bounds error just report that you’re trying to 
access an element of a size zero array which is no good.

**Comment by bob-carpenter** [comment]
Will fix with #2129
