### ISSUE TITLE
truncation should fail in parser unless the cdf exists

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#1628]
Paul Buerkner on stan-users points out that a user-defined density function with truncation will pass the parser but fail during C++ compilation.

* [ ] update parser to check the CDF exists before generating truncated code
    * [ ] univariate
        * [x] bernoulli_logit
        * [x] binomial_logit
        * [x] hypergeometric
        * [ ] gaussian_dlm_obs
        * [ ] neg_binomial_2
        * [ ] ordered_logistic
        * [ ] poisson_log
        * [ ] von_mises
        * [ ] wiener
        * [ ] categorical
    * [ ] multivariate outcomes
        * [ ] dirichlet
        * [ ] inv_wishart
        * [ ] lkj_corr_cholesky
        * [ ] lkj_cov
        * [ ] multi_gp
        * [ ] multi_gp_cholesky
        * [ ] multi_normal_cholesky
        * [ ] multi_normal
        * [ ] multi_normal_prec
        * [ ] multi_student_t
        * [ ] multinomial
        * [ ] wishart
* [ ] test models that should fail because of missing cdf
* [ ] update manual to explain how to write truncatable user-defined densities
* [ ] thank Paul in the acknowledgements

**Comment by paul-buerkner** [comment]
The problem might be slightly different. In the example I presented on stan-users, the CDF and CCDF are also defined in the functions block (otherwise the parser fails as expected). So, from my naive perspective, it does not seem to be the parser checks that are wrong but the internal usage of the user defined CDFs.

Here is the link to my post on stan-users containing the Stan code for whichs this occured:
https://groups.google.com/forum/#!searchin/stan-users/buerkner/stan-users/Tfw76L0ov8E/XkvHi4JdAQAJ

**Comment by bob-carpenter** [comment]
Thanks for clarifying.  I'll follow the link and make sure the behavior's right for Stan 2.9.
