### ISSUE TITLE
Too long scrolling list in stan_demo() that disappears off screen & makes selection difficult

### ISSUE THREAD

**Issue by rpnabar** [stan-dev/stan#1636]
When stan_demo() is invoked in R a very long list of examples scrolls on the screen. It is impossible to look at the list since the earlier examples scross off the screen buffer too.

Can we offer a better interface?

Other programs that do this either have hierarchical selection or wait for a key-press after each screenful of info. e.g. while selecting a CRAN or CPAN mirror.

**Comment by bob-carpenter** [comment]
Thanks for filing this as an issue.  Which version of
RStan are you using and in what interface (R terminal, GUI,
RStudio, ...)?  What I see in Stan 2.7.0 on the R GUI is this:

```
> stan_demo()
Do you want to download the example models? 

1: Download to include directory of the rstan package
2: Download to the temporary directory
3: Do not download

Selection: 
```

and then when I choose (2), it pops up a list just like
the CRAN mirror list.  And then I select a model and it
fails to compile (another issue).   At least in the R GUI.
The bigger issue is what happens when I select one.  I'm not 
a fan of built-in demos like this to begin with, especially
when the models don't work!

So what I don't understand is why you can't scroll
back in R.  My R terminal, GUI, and RStudio all let
you scroll back.

- Bob

**Comment by rpnabar** [comment]
Package:  rstan
       Version:  2.8.0
       Date:     Sep 16, 2015

R terminal on Linux Ubuntu

I cannot scroll back possibly because I'm logging in via ssh via Putty and 331 Lines seem a bit too much for Puttys screen buffer I think. I can scroll back to about the 100th example I think. 

Now I can probably also fix this by increasing Putty's screen buffer but that seems like an ugly hack. In any case dumping 300 odd examples at the user and then making him scroll back to line 1 seems non optimal IMO. 

I agree with your sentiment: This is a fairly hard to use way to throw examples as the user. 

In any case, its a minor usability bug. You guys probably have bigger fish to fry. :)

**Comment by jgabry** [comment]
I suppose we could make the user make additional selections, i.e., first
choose some category of example from a short list of categories, then
select the particular model from a list of only models in that category (or
even add subcategories if we wanted). This would take a bit of work (not
hard, perhaps tedious).

**Comment by bob-carpenter** [comment]
Moved to RStan issue tracker:  https://github.com/stan-dev/rstan/issues/220
