### ISSUE TITLE
Modeling a list of reals with uniform fails

### ISSUE THREAD

**Issue by ariddell** [stan-dev/stan#1664]
Just stumbled upon this one. 

This fails for me with rejecting initial values:

```
parameters {
  real s1[2];
}
model {
  for (i in 1:2)
    s1[i] ~ uniform(1.28, 1.48);
}
```
Yet this works fine
```
parameters {
  real s1;
}
model {
  s1 ~ uniform(1.28, 1.48);
}
```

Stan 2.8

I know it's not necessary to explicitly model params with uniform distributions -- but I suspect many of our gentle users will prefer to be explicit about such things.

**Comment by syclik** [comment]
That's not surprising. 

The right way to do it is to put constraints on the parameters. 

The reason this example fails is because Stan initializes the unconstrained parameters uniformly from -2 to 2. For your variables, the unconstrained are the same as the constrained variables. In the second example, the initialization finds the region with probability mass. The chance of randomly initializing in that window is 0.2 / 2.0 = 0.1. In 100 tries, there's a good chance it finds that region. 

In the first model, the chance of initializing in that window is much smaller with two variables: 0.01. In a hundred tries, it might or might not initialize there.

Remember, there's no gradient information outside that region, so no real help to HMC / NUTS to help find a starting point. 


If you want to see it work with the uniform distribution, change the bounds to -2, 2 or even anything with more area. (I'd still suggest against this.)

**Comment by ariddell** [comment]
So it was just dumb luck that it worked with the second case? I thought there might have been some special handling.

My path through the manual was unfortunate. I went straight to 47.1 Uniform Distribution where there's no mention of the constraint being required. I see the warnings everywhere else now.

I imagine if there was an easy way to detect this kind of programming error (failing to match support to constraints) it would have long since been included.

**Comment by syclik** [comment]
(Sorry -- I did my math wrong. It's 0.2 / 4.0 = 0.05, but the concept still
holds. You should be able to initialize the second model most times, but
you might still fail. The first model will fail much more often than not,
but if you ran it enough times, it'll initialize.)

I don't think there's an easy way to detect it because the Stan language is
so general which allows the bounds to be parameters or functions of data
and parameters.

**Comment by betanalpha** [comment]
Right — the best we can do is spot constrained distributions
and warn users that the corresponding parameters should
be constrained.  I suggested this recently for the uniform
as most of its uses are from new users and so the false
positives wouldn’t be so bad, but it’s a fine line to walk
where/when to offer automated “suggestions”.

**Comment by ariddell** [comment]
So it wouldn't be too difficult to just offer a warning if an unconstrained parameter is being used with a constrained distribution? Seems like a good idea to me -- especially since this is something specific to Stan (those coming from JAGS and WinBUGS might be caught by it).

**Comment by betanalpha** [comment]
Oh, no, that would be harder because various transformations can
take place in between the parameter declaration and its use in a
density.  I had just suggested a warning for _any_ instance of a
uniform distribution.

**Comment by ariddell** [comment]
Got it. But can we suppress the warning if uniform is being used with a constrained param?

**Comment by betanalpha** [comment]
Not sure — it might be hairy with the parser.  Also, this was all
just a suggestion that never really went anywhere.

**Comment by bob-carpenter** [comment]
Afraid not for all the reasons Michael said.  This
is a consequence of Stan's generality (it's Turing
complete, so even simple conditions that allow functions
like constraints are undecidable).

We might be able to have some heuristics.

It's the same issue as with the "Jacobian required" thing.
I can tighten that up a bit more, but we can't really
diagnose whether a user's transform is linear or not.

- Bob

**Comment by ariddell** [comment]
Could a warning be generated if there are no constrained parameters and there's a distribution being used with constrained support? It seems like that might go a long way if it could be detected at compile time.

**Comment by bob-carpenter** [comment]
It does 100 attempts to initialize if that wasn't clear,
which is why you can get to even a narrow range with luck
initializing in (-2, 2).  If it were uniform(10, 12) you'd
never get there with the defaults without the constraint.

There's another issue where I'll add a warning to
every use of the uniform distribution.

The bit about constraints is the single most important
thing people need to understand about Stan --- it probably
accounts for about 1/3 of our mailing list traffic that's
not about installs.

- Bob

**Comment by bob-carpenter** [comment]
Yes, that could be done.  We really have to check if
there are variables declared without lower and upper
bounds.  I've seen quite a bit of this on the list:

  real<lower=0> sigma;

  sigma ~ uniform(0, 1000);

That usually won't cause a problem with our default
inits, but the other way's problematic with defaults:

  sigma ~ uniform(0, 0.001);

- Bob
