### ISSUE TITLE
Error: no member named 'deep_copy' in namespace 'stan::model'

### ISSUE THREAD

**Issue by to-mi** [stan-dev/stan#1754]
I'm running rstan (Version 2.9.0, packaged: 2016-01-05 16:17:47 UTC, GitRev: 05c3d0058b6a) and R version 3.2.3 (2015-12-10) on Mac OS X.

With the simple test model:
````
data {
  matrix[5, 2] X;
}

transformed data {
  matrix[5, 2] Xt;

  Xt <- X;
  Xt[,2] <- Xt[,2] / sd(Xt[,2]);
}

parameters {
  real a;
}

model {
  to_vector(Xt) ~ normal(a, 1.0);
}
```

I'm getting the following error:
````
Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! file3ae4a3a3ab.cpp:74:38: error: no member named 'deep_copy' in namespace 'stan::model'
                        stan::model::deep_copy(divide(stan::model::rvalue(Xt, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), "Xt"),sd(stan::model::rvalue(Xt, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list())), "Xt")))), 
                        ~~~~~~~~~~~~~^
1 error generated.
make: *** [file3ae4a3a3ab.o] Error 1
````

My naive search of the repository for deep_copy.hpp in GitHub seems to indicate that 
`#include <stan/model/indexing/deep_copy.hpp>`
is only present in the test case for deep copying but nowhere else.

**Comment by bob-carpenter** [comment]
Thanks for reporting with a reproducible error and diagnosing the problem.

I was able to reproduce the error in RStan 2.9.0 and the current development version of CmdStd.  I'll fix by adding appropriate include (and integration test) ASAP.  We'll be able to roll out a quick fix, but it'll take a while to propagate through CRAN.

**Comment by bob-carpenter** [comment]
I figured out what's going on and am fixing in a bugfix branch.  There wasn't a test model for all the empty index cases (R style).  So I'm adding those and fixing the resulting assignment errors.  Should be done soon.

**Comment by to-mi** [comment]
Thanks! The new R-style indexing is great and makes code cleaner.

**Comment by behinger** [comment]
this exact problem still occurs with stan 2.9.0-3 (here tested with the code of "to-ml", but in my own models as well).


Do I need to compile the develop branch from source in order to get the bugfix? I used the CRAN version and the install_github develop branch so far.

Is there a particular use-case scenario that crashes the compiler?


`Error in compileCode(f, code, language = language, verbose = verbose) : 
  Compilation ERROR, function(s)/method(s) not created! file4637398b3b93.cpp: In constructor ‘model4637207f932e_2b312211b9bbe4eb97ea4a07ca409b1c_namespace::model4637207f932e_2b312211b9bbe4eb97ea4a07ca409b1c::model4637207f932e_2b312211b9bbe4eb97ea4a07ca409b1c(stan::io::var_context&, std::ostream*)’:
file4637398b3b93.cpp:74:25: error: ‘deep_copy’ is not a member of ‘stan::model’
make: *** [file4637398b3b93.o] Error 1
In addition: Warning message:
running command '/usr/lib/R/bin/R CMD SHLIB file4637398b3b93.cpp 2> file4637398b3b93.cpp.err.txt' had status 1 `

**Comment by bob-carpenter** [comment]
The pull request to fix this has been merged on the Stan
side.  So to build RStan with the fix, you'd need to make
sure that stan as a submodule of rstan is up to date with develop.

- Bob
