### ISSUE TITLE
truncation of generated quantities?

### ISSUE THREAD

**Issue by drbenvincent** [stan-dev/stan#1841]
Sorry if I've missed this from the manual, but is it possible, in the `generated quantities` block to generate samples that are truncated?

Toy example:

    generated quantities {
      real <lower=0,upper=0.5> epsilon_group;
      epsilon_group <- beta_rng(a,b);
    }

I get an error like this, from matlabstan:

    output-1.csv: Exception: hierarchicalNOMAG_model_namespace::write_array: epsilon_group is 0.905967, but must be less than or equal to 0.5
    output-1.csv: Diagnostic information: 
    output-1.csv: Dynamic exception type: std::domain_error
    output-1.csv: std::exception::what: hierarchicalNOMAG_model_namespace::write_array: epsilon_group is 0.905967, but must be less than or equal to 0.5
    Warning: Stan seems to have exited badly. 

I also tried something along the lines of:

    generated quantities {
      real <lower=0,upper=0.5> epsilon_group;
      epsilon_group <- beta_rng(a,b) T[0,0.5];
    }

but this does not compile...

    PARSER EXPECTED: ";"

I'm using cmdstan v2.9.0, via matlabstan 2.7.0.0

**Comment by bob-carpenter** [comment]
No, it's not possible to do truncated sampling.
You could do your own rejection sampler,

  epsilon_group <- -1;
  i <- 0;
  while (epsilon_group > 0.5 && i < 1000)
    epsilon_group <- beta_rng(a, b);
    i <- i + 1;
  }
  // epsilon_group = -1 if couldn't draw with rejection


But otherwise, we don't have a good way to do it unless
you can do it yourself.  We don't have inverse CDFs, though,
so it's not so easy.

**Comment by drbenvincent** [comment]
Cool. Thanks for that - that answers my question.
