### ISSUE TITLE
Limit the minimal NUTS tree depth

### ISSUE THREAD

**Issue by alyst** [stan-dev/stan#1893]
Is it possible to set the minimal tree depth for the NUTS sampler?

#### The rationale.
I observe that on some datasets some of the NUTS chains (~25%) finish in just 1 minute, while the others take around 30 minutes. That results in high Rhat statistics (5.0-15.0). When I extend the adaptation and sampling periods (from 8000/2000 to 16000/4000) the number of such "fast" chains is reduced as well as the Rhat (1.0-2.0).

I suspect these chains are fast because their treedepths are low, and that leads to degenerated samples. My hope is that if I can constrain the treedepth to be not less than 7 or 8, I can get decent Rhat with fewer samples much more often. Of course, increasing the number of iterations would also help, but since I apply the model to >10000 datasets the compute cluster time is a very precious resource.

#### Additional Information:
I use NUTS sampler, 8 chains in parallel, maximal treedepth is set to 9.

#### Current Version:
v2.9.0

**Comment by syclik** [comment]
@alyst, I'm closing this issue since it isn't an issue.

The posterior geometry is defined not only by the Stan program, but it's also data dependent. Given data, different Stan programs will behave differently. Given a Stan program, performance will matter depending on the data.

When you see high Rhats like you're describing, parameter values are getting stuck in different modes and Stan is correctly diagnosing that you have not converged. It's not really a function of treedepth.

If you have more comments, please go to the user list. Thanks.
