### ISSUE TITLE
Statistical efficiency is much lower now than in v2.9.0

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#1906]
#### Summary:
We're getting roughly half of the statistical efficiency for simpler models in the develop branch relative to v2.9.0.

#### Description:
Changes to warmup and sampling in NUTS has made it much less statistical efficient. I think it might be down to pull request #1848, but it could be somewhere else.

#### Reproducible Steps:
Run the bugs vol1 bones example with 100 chains on v2.9.0 and develop. You'll see about half the statistical efficiency (n_eff / s).

#### Expected Output:
I expect the n_eff / s to be roughly the same.

#### Additional Information:
If there isn't a use case where the changes to adaptation / sampling are much more robust, I'd suggest we roll back to the code in v2.9.0 until after we release v2.10.0.

#### Current Version:
e51e1a

**Comment by betanalpha** [comment]
To figure this out you can’t just aggregate chains naively like that.
You have to look at each chain individually to see what’s going on.

From what I can tell there are cases where the new variant is getting 
stuck in the tails in warmup for some seeds, which causes biased
mass matrix estimation and hence the poorer effective sample size.
You should be able to see this by comparing the mass matrix elements
from each chain to see if there are outliers depending on the seed.

The problem is that I can’t find anything wrong with the sampler that
would be causing this (there is one small bug, I think, but it doesn’t
manifest here).  Writing everything out by hand the sampler is picking
the correct points every time, it’s just that those points are not as far
from the initial point as in the old sampler (marginally the slice sampler
should pick the same points, but it looks like it has a higher variance
and hence more likely to jump out further from time to time, kind of
like an opposite Rao-Blackwell).  

In particular, I’m not convinced that the old sampler isn’t missing
something — if not a small mode than a heavy tail.  Indeed the energy 
diagnostic is hinting at a heavy tail that the old sampler might be missing
(in both variants of the sampler).

**Comment by syclik** [comment]
I was aggregating behavior just to see whether I could reliably see this
problem (which I can). I had run it 10 chains at a time and see a similar
behavior. I completely agree that to hunt it down, we need to get down to
the chain-level behavior. If you look at the single-chain behavior of
bones, most of the chains are at 1000 n_eff for the old and ~400 for the
new.

I believe you when you say that the old sampler might be missing something
where the new one is getting it right. I'd just like to see an example of
it before I'm confident of it. Just one compelling example will do it for
me.

On Wed, Jun 8, 2016 at 5:41 PM, Michael Betancourt <notifications@github.com
> wrote:

> To figure this out you can’t just aggregate chains naively like that.
> You have to look at each chain individually to see what’s going on.
>
> From what I can tell there are cases where the new variant is getting
> stuck in the tails in warmup for some seeds, which causes biased
> mass matrix estimation and hence the poorer effective sample size.
> You should be able to see this by comparing the mass matrix elements
> from each chain to see if there are outliers depending on the seed.
>
> The problem is that I can’t find anything wrong with the sampler that
> would be causing this (there is one small bug, I think, but it doesn’t
> manifest here). Writing everything out by hand the sampler is picking
> the correct points every time, it’s just that those points are not as far
> from the initial point as in the old sampler (marginally the slice sampler
> should pick the same points, but it looks like it has a higher variance
> and hence more likely to jump out further from time to time, kind of
> like an opposite Rao-Blackwell).
>
> In particular, I’m not convinced that the old sampler isn’t missing
> something — if not a small mode than a heavy tail. Indeed the energy
> diagnostic is hinting at a heavy tail that the old sampler might be missing
> (in both variants of the sampler).
>

**Comment by betanalpha** [comment]
In particular, take a look at the lp__ traces and see if there’s
any indication of multi modality.  In the models where I’m seeing
lower effective sample sizes I’m seeing what look like clusters.

**Comment by betanalpha** [comment]
blocker definitely has these same properties — in both
variants of the sampler lp__ clusters and the energy 
diagnostic is crazy bad.  The mass matrices seem to
be similar, but the new sampler actually achieves the
target acceptance probability of 0.8 whereas the old
sampler is biased high, above 0.9.  These leads to a
step size difference which could be accounting for
some of the differences.

**Comment by betanalpha** [comment]
I’m going to flip it and require that you provide a compelling example
where the new sampler is clearly doing something wrong on a model
with no indications of pathologies.

**Comment by betanalpha** [comment]
The difference in effective sample size seems to be
entirely due to the new sampler getting �stuck� occasionally.
See the lp__ or sigmasq_delta traces.  I see it with seed=48485
and random inits.

Setting adapt delta=0.93 in the new sampler yields 
nearly equivalent step sizes in both cases and gets
rid of the sticks.  The effective sample sizes look smaller
on average, but you have to look at the distribution of
effective sample sizes.  In the new sampler they�re
more uniform where as in the old sampler they�re more
variable, and we know that variable effective sample
sizes is a strong indication to not necessarily trust the
higher end of those effective sample sizes (as they�re
most likely computing the effective sample size of the
posterior conditioned on the slower parameters, not
the proper marginal posterior).

**Comment by betanalpha** [comment]
So I went back to a 100 dimensional Gaussian and the
reduction in effective sample size persists.  The problem
is that the old algorithm uses the �delayed rejection�
transition discussed on page 12 (equation 10) of the NUTS 
paper, where as the new algorithm does not.

Unfortunately I do not understand that trick yet.
�Preserving an uniform distribution� without actually
uniformly sampling is not making sense in my head.
If I can figure it out then I�ll update the new algorithm.

Do we want it in a separate PR or to be bundled into
the old PR?

**Comment by syclik** [comment]
Thanks, Michael.

I think a separate PR sounds good. We can get that other one in as soon as
there's some doc.

On Thu, Jun 9, 2016 at 8:31 AM, Michael Betancourt <notifications@github.com

**Comment by betanalpha** [comment]
I spent the afternoon working through the math, and while I still don't quite understand it intuitively I think I have a handle on it mathematically.  In the attached doc I show that two transitions leave the correction distribution invariant -- the first corresponds to what is in develop while the latter corresponds to the NUTS paper.  Anybody checking my work would be highly appreciated.

Ultimately the alternative transition induces anticorrelations which help to compensate for the fact that the No-U-Turn criterion tends to terminate too early in most cases (by about of factor of 2 in integration time).  I'm not sure if this combination is always optimal, but it at least reproduces what we had before.

The fix is actually really easy to implement, and I checked that it works locally.  Once #1904 has been addressed this will be an easy update.

[tree_sampling.pdf](https://github.com/stan-dev/stan/files/307389/tree_sampling.pdf)

**Comment by bob-carpenter** [comment]
Awesome.  Thanks for tracking this down.  The upshot
is that I now have a much tighter understanding of what
NUTS is actually doing as written in the paper and what
your multinomial version is doing.  I take it you can
weight by the weights, and not just the counts for the
multinomial thing and still get the same kind of reversibility.
I also can't quite see it intuitively because it seems that if
theta1 moves to theta2 in the last doubling then if they're
close to each other, the elements past them will make a difference
on the last doubling acceptance probabilities.

I'll continue to mull it over and go over your derivation more
closely.

- Bob

**Comment by betanalpha** [comment]
The derivation used the weights directly, not just counts,
so will work in any case provided that the weights have
the right marginal distribution.

**Comment by bob-carpenter** [comment]
It does seem like the underlying sampler on which the
boosted tail thing will work should distribute through
this construction.  But that principle is hard for me to
think about formulating.

- Bob
