### ISSUE TITLE
Cannot find parameter with user defined initial values

### ISSUE THREAD

**Issue by fisherc2** [stan-dev/stan#2237]
#### Summary:

CmdStan cannot find parameter when providing user defined initial values. 

#### Description:

I have been correspoding with @goedman, the developer of stan.jl, to figure out a problem with a parameter not being found when initializing Stan with user defined values. It appears that the problem might be with CmdStan. 

#### Reproducible Steps:

The necessary code and inputs to reproduce the error is attached below.
[tmp.zip](https://github.com/stan-dev/stan/files/809059/tmp.zip)

#### Current Output:

Here is the specific error message:
 

> Initialization from source failed.
> variable omega missing
> 

#### Expected Output:
The output should be standard output for posterior inference. 

#### Additional Information:
In case its relevant, I am using Ubuntu 16.04
Julia .5
#### Current Version:
v2.14.0

**Comment by goedman** [comment]
Just to help out here, after building the ./Testmodel executable, each chain is run using a command like:

`./TestModel sample num_samples=1000 num_warmup=200 save_warmup=0 thin=1 adapt engaged=1 gamma=0.05 delta=0.88 kappa=0.75 t0=10.0 init_buffer=75 term_buffer=50 window=25 algorithm=hmc engine=nuts max_depth=10 metric=diag_e stepsize=1.0 stepsize_jitter=1.0 random seed=-1 init=TestModel_1.init.R id=1 data file=TestModel_1.data.R output file=TestModel_samples_1.csv refresh=100`

Regards,
Rob

**Comment by syclik** [comment]
Thanks @goedman.

@fisherc2, sorry about that. I verified that it fails with the tagged version of CmdStan 2.14.0. The current `develop` version of CmdStan works fine. I'm not sure exactly what's changed between then and now. It's probably something to do with the Stan library and not CmdStan, but I can't be sure.

The quick workaround is to download the current version of CmdStan. We haven't discussed a release date of a new version. It's not straightforward to do a patch release with the large code changes since 2.14.0, so I don't think we'll be able to quickly release a version that fixes this immediately.

That said, your model seems to run quickly without initialization. Hopefully you can just leave off inits for now.

**Comment by fisherc2** [comment]
@syclik, thank you for responding so quickly. We used this simple model as a test case. I'm going to see if initializing the parameters helps with some of my complex models with narrow priors. Thanks again.

**Comment by goedman** [comment]
@syslik Hi Daniel, thank you for your help. Just ran both the simplified model (Chris - @fisherc2  - reduced his full model to this simple test case that showed the same issue) and the full model on the development version on Git and can confirm both work fine on that version.

Chris, the full model takes about 3 mins on my machine. Let me know offline if you need help setting this up (not difficult at all, comparable to the tagged CmdStan) or want to see my results for comparison. I also made a few minor changed to the RUN_xxx scripts.

Regards, Rob

**Comment by syclik** [comment]
@goedman, thanks for verifying. I'm going to close the issue and tag it with the 2.14.0++ milestone. If lots of people run into this issue, we can send out word that there's something broken in CmdStan that's fixed on the develop version.
