### ISSUE TITLE
Can't use variables as dimension declarations in generated quantities

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#2350]
#### Description:

I believe that the parser is being too aggressive in not letting variables declared in the generated quantities block to be used as dimension declarations.

#### Reproducible Steps:

Try to parse
```
parameters {
  real x;
}

model {
  x ~ normal(0, 1);
}

generated quantities {
  int N_ppc = 10;
  real x_ppc[N_ppc];
  for (n in 1:N_ppc)
    x_ppc[n] = normal_rng(0, 1);
}
```

#### Current Output:

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:

non-data variables not allowed in dimension declarations.
     found variable=N_ppc; declared in block=generated quantities
  error in 'bug.stan' at line 11, column 14
  -------------------------------------------------
     9: generated quantities {
    10:   int N_ppc = 10;
    11:   real x_ppc[N_ppc];
                     ^
    12:   for (n in 1:N_ppc)
  -------------------------------------------------

PARSER EXPECTED: <list><integer data expression>","
```

#### Expected Output:

No parser errors.

#### Current Version:
v2.16.0

**Comment by bob-carpenter** [comment]
I understand why you'd want that to work.   We know from looking at the progrma that `N_ppc` is constant.  

Insisting on data as defined in the data block prevents the following situation where the size of a generated quantity variable can change iteration to iteration:

```
int N = theta > 0.5 ? 3 : 10;
real y_sim[N];
```
Now the size of `y_sim` depends on the value of a parameter `theta` and can thus vary iteration to iteration.  As with a lot of these issues, the root cause of the problem is allowing the conversion of real values to integer values (here most simply in the form of a conditional).  But in this case, if we *don't* allow these comparisons we won't be able to very easily compute indicator functions for event probabilities.

**Comment by bob-carpenter** [comment]
The only way I could see your example being made to work is if we somehow did enough static analysis to realize that by assigining `N_ppc` to a constant, it remains constant.  So we inherit constantness down through some (but obviously not all) integer variables.  This is similar, by the way, to the analysis of what is truly data inside a function call, for which we also need to trace assignments through programs.

**Comment by bgoodri** [comment]
One of these years, it will probably become necessary to rewrite Stan's
parser with the metaparse Boost library, which parses at compile time
rather than at runtime. I think it would make it easier to do static
analysis things.

**Comment by bob-carpenter** [comment]
I'll have to check it out.  The static analysis is going to have to happen over the AST no matter how we build it.  Right now, the parser converts the Stan program to an AST then generates code.  The question is at which point we want to try to enforce well-formedness.  Right now, that's all in the same pass, which makes these kind of trace-like analyses more difficult.  We could relax that convention, let all the integer sizes through, then do a pass at the end that checks which ones are acceptably fixed in terms of not varying with parameters.

What the current boost library does is let you build a parser with semantic actions without generating code (other than using metaprograms in the preprocessor).  Not sure what you mean by parsing at compile time rather than runtime.

**Comment by bgoodri** [comment]
It is a template metaprogamification of the old Boost parser.

**Comment by bob-carpenter** [comment]
Wow, that's extreme:

http://www.boost.org/doc/libs/master/doc/html/metaparse.html

It really is trying to do parsing in the preprocessor.  I'm very skeptical given how slow and limited template metaprograms are.

**Comment by betanalpha** [comment]
Given that we're not doing any other static analysis yet I'm going to close this.
