### ISSUE TITLE
compute generated quantities only when necessary

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/stan#2355]
#### Summary:

The generated quantities block gets executed every iteration when we only need it at the end.

We could leave it out of optimization until the last iteration

We can leave it out of sampling until after warmup.

*Warning*: Care will have to be taken if warmup is being saved.

#### Current Version:
v2.16.0

**Comment by bgoodri** [comment]
I think generated quantities is already skipped when sampling if
save_warmup = 0. So, we are really just talking about optimization and ADVI.

**Comment by betanalpha** [comment]
Generated quantities are computed when the constrained
parameters are requested as a method in the model instance.
That means at no point are they controlled by the algorithms.
It also means that you cannot calculate constrained parameters
or transformed parameters without also computing the generated
quantities.  

This means that generated quantities are _not_ computed during
warmup and they are computed during optimizing only because
optimizing tries to write the entire state down.

In order to avoid computing the generated quantities there we’d
need model methods that perform the constraining transformations
and compute transformed parameters separately of the generated
quantities.  And then you’d be dealing with the issue that the intermediate
output would have a different schema than the final output.

**Comment by rgerkin** [comment]
Andrew asked a question about this a while back.  Isn't implementing this still the path towards efficient all-in-Stan computation of out-of-sample model fit (e.g. by cross-validation)?  Or is there another way of doing this?

**Comment by bob-carpenter** [comment]
There's a separate issue to be able to run generated quantities standalone.  And it's on our short-term to-do list.  This one may not get done any time soon because most of the problems will be solved by just running generated quantities later.

**Comment by rgerkin** [comment]
@bob-carpenter Are you talking about #1641 or another one?

**Comment by sakrejda** [comment]
Just putting a note in here that the current design for [output](https://github.com/stan-dev/stan/wiki/Design:-Consolidated-Output-for-Sample,-Optimize,-ADVI,-and-Diagnose) seems to allow for this by splitting the generated quantities out into a separate stream.  We would probably need to track iteration/chain so things could be matched up later.

**Comment by bob-carpenter** [comment]
@rgerkin:  Yes, #1641

@sakrejda I keep thinking we want a more structured output for the samplers.  The problem is how to keep it generic enough---the fear was requiring too many implementations for the interfaces.

**Comment by sakrejda** [comment]
@bob-carpenter If you have specific implementation worries could you add them to the discourse discussion or the wiki? I want this to move forward so I can figure out more details as needed.

**Comment by bob-carpenter** [comment]
No worries for the standalone generated quantities.  This issue is for turning off generated quantities while optimizing or warming up.

You mean this discussion:

https://github.com/stan-dev/stan/wiki/Standalone-Generated-Quantities:-Functional-Specification

**Comment by sakrejda** [comment]
Nope, I mean this one (linked above): https://github.com/stan-dev/stan/wiki/Design:-Consolidated-Output-for-Sample,-Optimize,-ADVI,-and-Diagnose
