### ISSUE TITLE
Conditionally define parameters

### ISSUE THREAD

**Issue by jeffalstott** [stan-dev/stan#2377]
#### Summary:
Feature Request: Allow defining parameters in the parameter block only if we need them:
```
parameters {
    real mu;
    real sigma;
    if (use_student==1){
        real nu;
    }
}
```
#### Description:

I want to write a big complex model once, but have one part of the model be an option that I want to specify at run time. That part of the model is whether to use a distribution that normal vs. lognormal vs. student vs ... etc. Switching between them in the `model` block isn't hard. However, we will need to define parameters for -all- of them in the `parameters` block. 

To prevent the sampler for spinning off in space with the unused parameters, we need to define priors for them and sample with them, even if we're not going to use them to fit to data. Since the speed of the sampler scales superlinearly with the number of parameters, these unused parameters are coming at a cost. 

There is a way to hack it:
```
data {
    ...
     int distribution_type; //switch for which distribution to use
}

transformed data{
    int noise_distribution_n_parameters;
if (distribution_type==1){
    noise_distribution_n_parameters = 2;
}
if (distribution_type==2){
    noise_distribution_n_parameters = 3;
}
}

parameters{
    vector[noise_distribution_n_parameters] noise_distribution_parameters;
}

model{
if (distribution_type==1){
  noise_distribution_parameters[1] ~ ...
  noise_distribution_parameters[2] ~ ...
   err ~ normal(noise_distribution_parameters[1], noise_distribution_parameters[2]);
}
if (distribution_type==2){
 noise_distribution_parameters[1] ~ ...
 noise_distribution_parameters[2] ~ ...
 noise_distribution_parameters[3] ~ ...
   err ~ student_t(noise_distribution_parameters[1], noise_distribution_parameters[2], noise_distribution_parameters[3]);
}
}
```

It's super ugly, though, which is relevant for downstream code usability and maintenance. If the user (such as myself) is thinking "this model should have a parameter named `mu`", but it's only named  `noise_distribution_parameters[1]` then it creates lots of complexity and opportunities for muckups.

**Comment by bob-carpenter** [comment]
Thanks for submitting this as a pull request.

So far, Stan has clung pretty tightly to C-style declarations and static lexical scoping.  There aren't any conditional declarations in C (or C++ or Java).  R allows these:
```
> flip <- function() rbinom(1, 1, 0.5)
> if (flip()) y <- 10; y
[1] 10
> if (flip()) z <- 10; z
Error: object 'z' not found
```
This highlights two features of R:  (1) the body of a conditional does not introduce a local scope, and (2) variables are dynamically lexically scoped.

The way we're currently hacking it is a little different, and while it's a hack, it's a general way to code the conditional you're after (general in that it'll work for any type).  Here's how it'd look for student-T vs. normal if you want the degrees of freedom to be a parameter and you want completely different priors.

```
data {
  int<lower=0, upper=1> is_student_t;
  int<lower = 0> N;
  real y[N];
  ...
parameters {
  real mu;
  real<lower=0> sigma;
  real<lower=1> dof[is_student_t];  // size 1 if student t, 0 othewise
  ...
model {
  if (is_student_t)
    dof ~ normal(4, 4);
    sigma ~ student_t(4, 0, 3);
    mu ~ student_t(4, 0, 10);
    y ~ student_t(dof[1], mu, sigma);  // dof is size 1 if student t
  } else {
    sigma ~ cauchy(0, 2);
    mu ~ normal(0, 10);
    y ~ normal(mu, sigma);
  }
  ...

```
All of the parameter variables are visible in scope all the time, but the ones not being used with be arrays of size zero.  You can add an extra array dimension and select a variable this way for any type.

With conditionals on variables, the only difference is that the declaration above is replaced with
```
  if (is_student_t) 
    real<lower=1> dof;
```
and the usage is just `dof` instead of `dof[1]`.

I think the conditionals are a bit clearer here.  The only way I can see that we could code it is using the hack above internally.  It'd require reinstrumenting a whole bunch of print and warning statements to deal with when variables like `dof` had an extra dimension for selection.

**Comment by jeffalstott** [comment]
Thanks @bob-carpenter 
For my use case what you just wrote is indeed what I settled on since writing this issue. I'm more concerned about broader use cases with more complexity in what parameters are switching on and off. I respect the difficulty of actually implementing this, though!

**Comment by bgoodri** [comment]
There is nothing that has more complexity than rstanarm and we manage with
possibly-zero sized things.

**Comment by jeffalstott** [comment]
The question isn't whether one can manage (one can). The question is ease-of-use, which yields advantages in complexity, maintainability, and coder time. As a different example that is more commonly discussed, I'm of a similar mind to @andrewgelman in wanting to dictate the priors on parameters at the same moment I declare them
```
parameters {
    real mu ~ normal(0,4);
}
```

But I acknowledge that creating such user experiences requires more complexity behind the scenes.

**Comment by bob-carpenter** [comment]
I completely understand about wanting higher-level coding constructs.  And I agree.  It's why I started working on Stan in the first place!

Here, the higher-level coding construct's ease of use probably doesn't outweigh the fact that (a) it's an unusual programming language pattern (existing only in R as far as I know), (b) there's not an easy way to code this in C++, and (c) there's a relatively simple line-for-line workaround.

If someone figures out (b), how to code this in a way that doesn't incur a prohibitive amount of technical debt, we can revisit whether it's worth doing given (a) and (c).

P.S.  Adding sampling to variable declarations is easy.  There's just disagreement among the dev team about whether it's a good thing or not, because not every prior can be written as a one-liner, and now you have two places to go look for priors.  Anyway, that's a separate issue, so let's not hijack this thread.

P.P.S.  I'm thinking along the lines of something radically different than Stan that would support the kind of modularity we really need, which is plug-and-play priors.  This conditional parameter stuff is just a symptom of the larger problem of not having modular variable declarations plus priors that can be encapsulated in a reusable function.

**Comment by bgoodri** [comment]
In addition, declaring something in the parameters block and then not using
it in the likelihood is not a big deal in Stan, provided you have a proper
prior on it.

**Comment by betanalpha** [comment]
I would argue that all of these requests are coming from
a desire to specify multiple models within a single Stan
program (model being defined by parameter space, data
space, and joint density), but this is against the original 
abstraction of a Stan program specifying single statistical 
model.  Personally I very much prefer maintaining that
abstraction as I think that it is the correct approach, even
if it makes hacks like this harder.

**Comment by bob-carpenter** [comment]
I'm drifting off issue again, but what we really need is a way to be able to specify the bits that get reused across models.  As is, that's not so easy.  Cutting and pasting whole models to change priors is a terrible programming practice even if it produces nicer Stan models.  I don't have a solution for this.  Conditional parameters aren't sufficient to solve the bigger problem.

**Comment by khakieconomics** [comment]
@bob-carpenter Re. your joke above about this being submitted as a pull request--I'm probably to blame (I told Jeff he'd get feedback on the idea if he put it up as a feature request). What's the preferred format? Discourse?

**Comment by bob-carpenter** [comment]
No, this is perfect.  It's a crisply defined feature request in terms of functionality.

When things are vague, it's better to start on Discourse.  Also, I want to keep the threads on GitHub focused on the issue at hand and bigger design discussions tend to drift (partly my fault!).

**Comment by jeffalstott** [comment]
> ...what we really need is a way to be able to specify the bits that get reused across models.  As is, that's not so easy.  Cutting and pasting whole models to change priors is a terrible programming practice even if it produces nicer Stan models.

+1. +1000. I see the logic of a single, complete program per model, but it's hell if you're developing a bunch of models. The method used in `rstanarm` of slipping strings of code into different `.stan` files, with each option maybe needing to put strings into several different places in the file, is heroic, but not what one would build if one were optimizing for resuability.

**Comment by andrewgelman** [comment]
yup
