### ISSUE TITLE
Typos in the manual (maybe bugs in the code)

### ISSUE THREAD

**Issue by mahaa2** [stan-dev/stan#2453]
#### Summary:
Typos in the manual (maybe bugs in the code)

#### Description:
In Section 35.8 - Correlation matrix, some equations appear to be wrong.

First :
**tanh : R ─> (-1, 1)** instead of **tanh : R -> (0, 1)**

Second :
In absolute Jacobian determinant of the correlation matrix inverse transform, the partial derivatives appear to be wrong. It should read :
\dfrac{\partial tanh γ_{i, j}}{\partial γ_{i, j}} because z_{i, j} = tanh γ_{i, j}.

Third :
In correlation matrix transform (last row)
z_{i, j} = w_{i, j}*prod_{i' = 1}^{i-1} (1 - z_{i', j}^2)^{-1/2} for 1 < i < j

I hope this help other users.

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
Thanks.   We have an open issue for corrections to the manual, so I'm moving this there:

https://github.com/stan-dev/stan/issues/2437#issuecomment-354854834

I'll fix the manual before the next release.

The implementation of the correlation matrix constraint and Jacobian is in:

https://github.com/stan-dev/math/blob/c36cfa2becfcc2a0673addb1600e9133e822998d/stan/math/prim/mat/fun/corr_matrix_constrain.hpp

The second signature is used for the Jacobian calculation with the log density reference `lp` being incremented.  It works in two parts, calling the correlation constraint function (in `scal` rather than `mat` directory):

https://github.com/stan-dev/math/blob/c36cfa2becfcc2a0673addb1600e9133e822998d/stan/math/prim/scal/fun/corr_constrain.hpp

The relevant lines defining the derivative of tanh (on the log scale) are

```
template <typename T>
inline T corr_constrain(const T& x, T& lp) {
  T tanh_x = tanh(x);
  lp += log1m(square(tanh_x));
  return tanh_x;
}
```
So that's 
```
d/dx tanh(x) = 1 - tanh(x)^2
```
That agrees with Wolfram alpha:  http://www.wolframalpha.com/input/?i=d%2Fdx+tanh(x) (because `sech^2(x) = 1 - tanh^2(x)`).

**Comment by bob-carpenter** [comment]
Moved to manual issue comment: https://github.com/stan-dev/stan/issues/2437#issuecomment-354854834
