### ISSUE TITLE
Output from simulation study shows unexpected values

### ISSUE THREAD

**Issue by BATurlach** [stan-dev/stan#2487]
[StanProblem.txt](https://github.com/stan-dev/stan/files/1799196/StanProblem.txt)
[StanProblem.pdf](https://github.com/stan-dev/stan/files/1799193/StanProblem.pdf)

#### Summary:
The output of a generated quantity gives surprising results.

#### Description:
I was trying to implement a simulation study described in _The BUGS Book_ in Stan and the output was surprising.  The simulation study essentially is based on the question "Suppose costs of a repair have a gamma distribution with mean &pound;100 and standard deviation &pound;50: how many items will I be able to repair for &pound;1000?".

The program seems to be simple enough:  Generate gamma random variates with parameters &alpha;=4 and &beta;=0.04 and sum them up until the limit of 1000 is exceeded, then substract the count for the last generated random variate.

#### Reproducible Steps:
Run the attached R notebook (StanProblem.txt), after downloading it should be renamed StanProblem.Rmd and opened using RStudio.  The attached PDF file StanProblem.pdf shows the results that I obtain on my computer.  A student of mine reported similar results when running (an earlier version of) this notebook on his MacBook.

#### Current Output:
Shown in the attached PDF file.  

#### Expected Output:
I would have expected that the summary of the `y` values in the first section would be similar to the summary given in the second section, where only one gamma variate is generated.

I am a bit baffled which values are returned for `y` in the first example.  I would expect that it is the last generated variate in the `while()` loop.  That variate should be gamma with parameters &alpha;=4 and $beta;=0.04, whose theoretical mean and standard deviation are respectively 100 and 50.  The sample mean and sample standard deviation shown in the output is quite far from these theoretical values. 

#### Additional Information:
My apologies if this should have actually been reported as an  `rstan` issue rather than a `stan` issue.  The PDF file gives more information for my setup as it includes the information from `sessionInfo()` in `R`.

#### Current Version:
v2.17.1

**Comment by syclik** [comment]
Fun example. This isn’t a bug; the `y` across the two examples should be distributed differently. 

In the first example, if you save the first gamma random variable, that will have the properties you’re expecting: `y_first ~ gamma(4, 0.05)`. So why is your `y` not distributes this way? It’s because you’re getting the distribution `p(y | sum < 100 AND sum + y > 100)`.

There’s a quick way to reason that the expectation of this variable is larger than 100: you’d only could use the first random variable if `y_1 > 100`. And that continues for the rest of the subsequent draws. 

It’s a little too early in the morning (and I’m on my phone) for me to work out the analytic form if there is one, but I’d do it using simulation anyway.

**Comment by BATurlach** [comment]
G’day Daniel,

Of course! Length biased sampling! I should have known, but did not recognise it on this occasion. 

Thank you for your help.

Cheers,
Berwin
