### ISSUE TITLE
C++ exceptions from generated quantities cause shorter chain lengths

### ISSUE THREAD

**Issue by syclik** [stan-dev/stan#2568]
#### Summary:
C++ exceptions that come from the generated quantity blocks are not handled properly. This causes short chain lengths.

#### Reproducible Steps:
Here's a small Stan program that shows the issue:
```
parameters {
  real alpha;
}
model {
  alpha ~ normal(0, 1);
}
generated quantities {
  real<lower = -0.3> beta;
  beta = alpha;
}
```

#### Current Output:

In CmdStan, the number of rows in the output file is short. I see a lot of these messages:

```
Exception: foo_model_namespace::write_array: beta is -0.741171, but must be greater than or equal to -0.3  (in 'foo.stan' at line 8)
```

which are different than when there is an exception in other parts of the code:
```
Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
Exception: ...
```

#### Expected Output:
I except there to still be the number of draws specified.

#### Current Version:
v2.17.1

**Comment by bob-carpenter** [comment]
The issue needs to be updated to specify the intended fix.  I see two options:

1.  Reject the entire draw retroactively if generated quantities fails.  

2.  Report NaN for all values when there is an error in generated quantities.

3.  Abort the Stan run.

(1) is problematic.  because we've drawn the paramter values according to NUTS, and only *then* run into a problem.  So if we don't keep the draw according to NUTS, we're not appropriately drawing from the posterior.  The generated quantities don't affect the posterior.  I guess we could somehow make this salvageable by making this a rejection like in transformed parameter constraint violations.  

(2) draws from the posterior as specified by the model block.

(3) is what we used to do, reasoning that the errors were unrecoverable after the draw has been taken according to NUTS and the generated quantities fails.


What happens when there's an indexing error?

**Comment by seantalts** [comment]
Same for this one - @syclik has said this is blocking 2.18 so I want to make sure someone is assigned to it and working on it.

**Comment by syclik** [comment]
I think 2 is the way to go, but I haven’t dug into it yet. Not sure what
the right behavior is, but it shouldn’t do what it does now.

I’ll tackle the other one first.

**Comment by bob-carpenter** [comment]
If this is blocking, I suggest we move back to the old behavior and just stop the entire computation with an error message.

**Comment by bgoodri** [comment]
That is essentially happening in RStan anyway because it throws an error if
there are any NAs.

**Comment by syclik** [comment]
@bgoodri, can you unpack your last comment? Does that mean that RStan is expecting all the numbers to be not `NaN`? If so, what happens when it's `NaN`?

**Comment by bgoodri** [comment]
Yes, if anything is NA then the constructor of a stanfit object fails

https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/R/AllClass.R#L66

**Comment by syclik** [comment]
Does it need to fail?
