### ISSUE TITLE
Support function overloading in functions block

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/stan#2589]
#### Summary:
Currently overloading function in `functions{}` causes parsing error. Fixing this provides better UI.

#### Description:

This doesn't work
```Stan
functions {
  real foo(real[] y0);
  real foo(real[,] y0);
}
...
```

The fix is to have a single functor for `foo` which overloads `operator()`.

#### Current Output:
```bash
Parse Error.  Function already declared, name=foo
```

#### Expected Output:
Parse successfully.

#### Current Version:
v2.18.0

**Comment by VMatthijs** [comment]
I'm not sure I agree this is a good idea. Function overloading greatly complicates compiler design and might stall progress on other features we care about. There's a good reason a lot of strongly typed languages (e.g. OCaml) disallow this. There are principled solutions to allowing overloading, like type classes and modular implicits, but they are complicated. The current setup of only allowing library functions to be overloaded is already a bit tricky, but it's workable.

**Comment by bob-carpenter** [comment]
It was not a principled decision to disallow overloading, I just never got around to implementing it.  

I have a strong preference for supporting overloading.  Users keep trying it and getting tripped up.  Without overloading, users can't implement our library functions.

Is the complication just due to type inference?  We should be dealing with overloads the same way as C++, requiring a unique least-promoted match.  So if you have foo(int, double) and foo(double, int) and try
to pass foo(int, int), it's a mistake, because it's ambiguous.

**Comment by VMatthijs** [comment]
Of course, it can be done. You'd have to carry around a set of possible types for each expression in the semantic check, rather than a single type. You might even want to use a lazy set, in case we have a combinatorial explosion of possible types. It'd probably be a decent amount of work to thread that through everywhere, especially as we also want subtyping int<real.

**Comment by bob-carpenter** [comment]
> On Dec 13, 2018, at 9:46 AM, Matthijs Vákár <notifications@github.com> wrote:
> 
> Of course, it can be done. You'd have to carry around a set of possible types for each expression in the semantic check, rather than a single type.

That's exactly what we do now.  And it's what you must be doing with the built-in types already.

> You might even want to use a lazy set, in case we have a combinatorial explosion of possible types. It'd probably be a decent amount of work to thread that through everywhere, especially as we also want subtyping int<real.

We not only want to subtype int < real, we also want int[] < real[], and so on up for all the array types.    I never got fully covariant typing going, though it's been on my to-do list from the get-go.

**Comment by WardBrian** [comment]
Closed by https://github.com/stan-dev/stanc3/pull/1027
