### ISSUE TITLE
Severe memory leak when using compound arithmetic and assignment statements

### ISSUE THREAD

**Issue by lamhm** [stan-dev/stan#2753]
#### Summary:
Severe memory leak when using compound arithmetic and assignment statements.

#### Description:
When using a compound arithmetic and assignment statement inside a for-loop on a variable that has been declared outside the for-loop, it seems that STAN make a deep copy of the variable for every iteration of the for-loop. These copies are not released until the whole analysis finishes.

#### Reproducible Steps:
Try the following code (3-4 iterations for the MCMC are enough):

```
data {
    real any_number;  // Dummy data, just to meet STAN requirements
}
parameters {
    real dummy_param;  // Dummy parameter, just to meet STAN requirements
}
model {
    real dummy_variable = 0.0;
    int MAX_ITER = 50000000;  // 50 million
    for (i in 1 : MAX_ITER) {
        dummy_variable += 1.0;
    }

    // This is to make sure that the posterior will be proper,
    // so that STAN does not complaint.
    dummy_param ~ normal(0, 1);
}
```

#### Current Output:
On my system (Ubuntu 16.04), STAN consumed **2.2 GB** of RAM for the simple model above.

#### Expected Output:
The model above should consume only MBs (if not KBs) of RAM.

#### Additional Information:
I have tried to run the above code with RStan and CmdStan. The results were the same.

#### Current Version:
v2.19.1

**Comment by wds15** [comment]
How does 2.18.1 behave with this?

**Comment by syclik** [comment]
The behavior you are describing is not a memory leak. It's not a deep copy either. 

What you're seeing is due to the autodiff stack increasing in size. Inside the model block, the variables declared are declared in c++ as autodiff variables. Every operation to those variables contributes to the expression graph. This expression graph is built up then used when the gradients are computed, at which time the memory is recovered. 

If you moved the declaration and the for loop into tranfoed data, you should see that the memory is under control.

Does that make sense?

**Comment by lamhm** [comment]
The problem is I am building a discrete-time model. So, I need a similar for loop inside either the `model` block or the `transformed parameters` block. I have tried to put the code in the `transformed parameters` block. The result is the same.

Any suggestions to get around this?

Thanks a lot.

**Comment by wds15** [comment]
Maybe you post your model on discourse?

**Comment by lamhm** [comment]
I have more than 500 lines of code for the moment. So I feel it would be too much for anyone to go through my code and digest it.

What I am trying to achieve is to simulate the weekly numbers of observed dengue cases at a hospital within 10 years, using a discrete-time SIR-liked model. These simulated numbers will then be fitted to the hospital data to estimate the time-dependent transmission rates of dengue. There are many more details that make the simulation a complex process. But the main parameters that need to be estimated here are the transmission rates. The purpose of the "simulation" is only to transform the transmission rates into weekly cases. But the simulation process needs to create a lot of intermediate variables (which are not necessary to be kept track) because there are a lot of interaction between the classes in my model. And because it is a discrete-time model, I have to loop through time.

At the moment, I cannot run my model because it requires too much RAM (I have 32 GB of RAM on my desktop).

**Comment by wds15** [comment]
Sure. In any case the discourse forum is the right place to seek support on modelling question. This isn't a bug or feature request for Stan, but a problem with modelling.

Thus the forum is the right place to seek support. 500 lines of code is too much, yes... but maybe you can simplify things so the gist of it is possible to demonstrate with much less? 

Please close this issue if you agree that this is a modelling issue rather than a legit issue.

**Comment by wds15** [comment]
OK... one last comment... there is a way in Stan to decrease the size of the expression graph in Stan. If you execute the for loop above using map_rect in the Stan language then the expression graph is behind the scenes evaluated in small pieces and things may actually work... but you would have to code things such that the map_rect is called with some number of shards and each work shard would return the final log-lik. This way the AD tree is processed in smaller chunks.

(But now I will stop more advise here on this modelling as this could be interesting to others)

**Comment by lamhm** [comment]
Thanks a lot for your support. I will close the issue now.
