### ISSUE TITLE
Add inline specifier to stable_sum

### ISSUE THREAD

**Issue by fatvlady** [stan-dev/stan#2772]
#### Summary:
Within [base_xhmc.hpp](https://github.com/stan-dev/stan/blob/develop/src/stan/mcmc/hmc/xhmc/base_xhmc.hpp) `stable_sum` function should be marked inline.

#### Description:
`stable_sum` function is not marked with `inline` specifier, which causes duplicate symbol errors when compiling several translation units. Furthermore, function body is rather small, so inlining could potentially make its calls more efficient.

#### Current Version:
v2.19.1

**Comment by bob-carpenter** [comment]
Thanks for reporting.  It should be fixed.  There are three other things I noticed when taking a look:

* it should use `log1p(e)` rather than `log(1 + e)`

* (nice to have) the function should be in its own file or in an `internal` namespace

* (nice to have) multiple translation unit tests along the lines of the one we have for the math library;  not sure what the top-level include would be for this, though---maybe the services?



I don't think our multiple translation unit tests extend to things defined in the model.  @syclik --- should this also add multi translation unit tests for all of the algorithms, services, etc.?

**Comment by fatvlady** [comment]
Thanks for your reply. I am not sure regarding `log1p` - this will likely change the resulting numbers, which in its turn might influence the way XHMC algorithm behaves. So my guess is that it is better to fix within separate issue. Besides, it does not seem trivial whether `stable_sum` will retain stability after switching from log-weights to weights. And if using weights instead of log-weights, `log1p` calculation can be avoided at all.
There are also some other minor problems that can be fixed within this issue, e.g. `stable_sum` can return pair of doubles instead of assigning to `double&` arguments, and `build_tree` has wrong return type, should be `bool`.

**Comment by wds15** [comment]
I doubt that weights on the natural scale instead of the log scale are a good idea.

**Comment by fatvlady** [comment]
@wds15 It is obviously safer to use logarithmic scale, but my reasoning was that log-weights are actually differences between starting value of Hamiltonian and terminal points at tree leaves. Since during tree traversal we only evolve integrator, trajectory approximately conserves Hamiltonian value and exponent of difference between energies is definitely within floating point range. Maybe I am missing something though.

**Comment by wds15** [comment]
If I recall right, then this was exactly the logic which @betanalpha applied in a never released rewrite of NUTS. It was never released because we saw major issues with this approach. I am not too familiar with the codes, so maybe my memory is wrong - but I think this was tried with the same reasoning and it failed.

**Comment by betanalpha** [comment]
Making the function inline won’t cause any problems 
so if it fixes translation unit issues then there’s no
issues on my end.  But really this is a function used
just for this (non-exposed) implementation so an 
internal/anonymous namespace would be just as 
good.

Using log1p is appropriate.

Everything should be kept on the log scale as 
currently implemented in the function — the weights 
are proportional to the exponential of differences in 
the Hamiltonian and will easily underflow or overflow.

**Comment by bob-carpenter** [comment]
Yes, log1p will change exact numerical results, but they should be better.  It's not a necessary fix for this PR.

**Comment by betanalpha** [comment]
The exhaustive sampler has always been experiment and has never
been exposed to any of the interfaces so I don’t consider exact
numerical results sacred here.  There may be one or two unit tests
that depend on exact numerical results but they can easily be changed.
On the other hand since this hasn’t been exposed optimizing to use
log1p might also not matter!

**Comment by fatvlady** [comment]
The only remaining question is testing then. Services obviously does not include this experimental file, therefore the only appropriate solution I see is to create another multi-unit test which includes all `base_*.hpp` from `mcmc` folder. Is that fine?

**Comment by bob-carpenter** [comment]
Yes, any kind of testing you could add would be great.

Going forward, I think we're going to start consolidating multiple
functions into single files more often.
