### ISSUE TITLE
stan::io::json parser is 10x slower than python's ujson

### ISSUE THREAD

**Issue by seangoogle** [stan-dev/stan#2776]
#### Summary:
I dumped a 300k x 100 matrix into a json file and had python's ujson load it (5.6s) and then loaded it in CmdStan (67.3s). Seems like we could switch to a 3rd party json parser or another format for better speed. 

For comparison, reading the equivalent .data.R rdump file takes 36s (still not great).

#### Current Version:
v2.19.1

**Comment by bob-carpenter** [comment]
Is that using the same JSON format for output?  

Is that just I/O or does it include conversion to some Python data format?  That is, is the bottleneck in our I/O or in our var_context?  

Is it something we can pull out a C++ implementation from and use in Stan (license and interface)?

**Comment by bob-carpenter** [comment]
Thanks for testing, by the way---it seems rude now that I look at it to just fire back a bunch of cross-exam questions!

**Comment by seangoogle** [comment]
I'm not sure I understand your first question. It's the same exact file. 

The ujson module includes conversion into Python dictionaries and lists, etc. I don't know where the Stan bottleneck is.

There are many fast C++ json parsers. I suspect some of them could be included. I don't have opinions on which ones to use.

**Comment by bob-carpenter** [comment]
There weren't when we wrote this one.

> On Jul 3, 2019, at 1:00 PM, seangoogle <notifications@github.com> wrote:
> 
> I'm not sure I understand your first question. It's the same exact file.

Yes.  That answered my question.


> The ujson module includes conversion into Python dictionaries and lists, etc. I don't know where the Stan bottleneck is.

My guess is either conversion to Python or the basic ASCII to double conversion, because profiling showed our C++ code spends almost all of its time in ASCII to double conversion.


> There are many fast C++ json parsers. I suspect some of them could be included. I don't have opinions on which ones to use.

We couldn't find any back in 2014 or so when Mitzi and I wrote the event-based one that's there now.  All the open-source ones we could find built DOM-like trees and had very limited handling of floating point.

**Comment by rok-cesnovar** [comment]
Just throwing a few references here: 

- this benchmark covers a lot of the libraries https://github.com/miloyip/nativejson-benchmark

- this paper by Microsoft researchers claim that Mison can parse to speeds up to 2GB/s http://www.vldb.org/pvldb/vol10/p1118-li.pdf
- https://lemire.me/blog/2018/05/03/how-fast-can-you-parse-json/ a blog post with benchmark code claiming you can parse a GB of data in 2 to 3 seconds

We are interested in full precision so who know how all of this transfers.

**Comment by rok-cesnovar** [comment]
Just a heads up so we dont duplicate with anyone. I am tackling this. I profiled the original cmdstan code and am trying out the libraries for now (outside cmdstan). Will keep you posted.

**Comment by bob-carpenter** [comment]
If we go with an external library, should it be in `cmdstan` or `stan`?  Same question if we keep our library.  I don't know if PyStan or RStan are going to use the `stan-dev/stan` JSON parser given that the languages have one built in.

**Comment by rok-cesnovar** [comment]
I guess it makes sense to move it out to cmdstan, if its the only place its being used. 

I tried a few different size JSON files (from 200MB to 2GB, generated based on the example here https://discourse.mc-stan.org/t/any-way-to-make-stan-competitive-with-tensorflow-for-maximum-likelihood/8230/13).

90% of the parsing time is spent in the `parse_number()` function, inside which ~55% is spent on `boost:lexical_cast`, ~20% on waiting for the next non whitespace charcter and ~25% on everything else.

On my machine parsing a ~200MB JSON file takes 35s, compared to parsing the exact same file in python with ujson takes 2s, for a 2GB file its 370s vs 26s.

I tried replacing `boost::lexical_cast` with [`std::stod`](https://en.cppreference.com/w/cpp/string/basic_string/stof) and [`std::stoul`](https://en.cppreference.com/w/cpp/string/basic_string/stoul) which reduced the parsing time for about 20%, but that was all I could get. There are reasons you would not want to do that switch from lexical_cast (see https://stackoverflow.com/a/23582634), but I think none of those apply to our case. 

This opens the question whether we want to replace the `boost::lexical_cast` with `std::stod` and `std::stoi` for the R dump, since it became available in C++11? 
The `lexical_cast` is not being used for a generic interface with templating, we dont need localization and parsing to an array of strings is not going to be memory efficient or even useful in the case of cmdstan.

**Comment by sakrejda** [comment]
There an issue parsing very small numbers with the standard lib functions but there's also a solution to it

**Comment by ahartikainen** [comment]
Was lexicalcast giving us problems when user had some locale setting where numbers use comma as a decimal separator?

    1,4 == 1.4

**Comment by rok-cesnovar** [comment]
> Was lexicalcast giving us problems when user had some locale setting where numbers use comma as a decimal separator?

Seems possible.

I am just about to open a PR in 5 minutes for this. It will be a WIP because I dont want to do a cleanup before it is confirmed.

@ahartikainen I ultimately decided to go with RapidJSON. The main reason was that their C++ API is much easier to follow, has examples, docs. And also the [license](https://github.com/esnme/ujson4c/blob/master/LICENSE.txt) in ujson4c doesnt clearly state what exact license they use. For RapidJSON its MIT, which I believe is OK, right?

And last but not least its also quite fast. I want able to get the ujson4c working, I tried https://bitbucket.org/awangk/ujson/src/master/ and it was slower than RapidJSON. But I think that library has no connection with python's ujson.

For the 200MB JSON we get from 35s to 2.5s with RapidJSON and for the 2GB we get from 350s to 25s on my system. For the latter file ujson in python takes 30s. So I think in terms of speed its fine.

**Comment by ahartikainen** [comment]
Sounds fast.

I don't think there is a big difference in C++ with rapidjson and ujson4c. I think most magic they do is with the Python <--> C++ interface.

**Comment by sakrejda** [comment]
> Was lexicalcast giving us problems when user had some locale setting where numbers use comma as a decimal separator?

@ahartikainen : IIRC with C++ when you read a very small number in scientific notation using one o the standard functions and reading something like 3.3e-314 it will drop the `-` and you get a huge number instead.. the function does set an error code somewhere and I ended up using `std::stod` which worked fine (you just have to catch 'out-of-range' errors..
