### ISSUE TITLE
what's the default prior distribution for the variable in parameter block ?

### ISSUE THREAD

**Issue by frozenxia** [stan-dev/stan#2837]
#### Summary:
what's the default prior distribution for the variable in parameter block? Someone says the default distribution is (-infty ,+infty ), but the sample output of variables in parameter block are near zero, why?

#### Description:

the stan code is as below:
``` python
data{
    int<lower=0> N;
    int<lower=0> K;
    matrix[N,K] x;
    vector[N] y;
}

parameters{
    real alpha;
    vector[K] beta;
    real<lower=0> sigma;
}

model {
    y ~ normal(alpha + beta *x ,sigma);
}
```
and the output of samples of **sigma** are belows:
```
 [0.00529388 0.00529388 0.00529388 0.00529388 0.00529388 0.00529388
 0.00529388 0.00529388 0.00529388 0.00529388 0.00529388 0.00529388
 0.00529388 0.00529388 0.00529388 0.00529388 0.00529388 0.00529388
 0.00529388 0.00529388 0.00529388 0.00529388 0.00529388 0.00529388
 0.00529388 0.00529388 0.00529388 0.00529388 0.00529388 0.00529388
 0.00529388 0.00529388 0.00529388 0.00529388 0.00529388 0.00529388
 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479
 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479
 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479
 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479
 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479
 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479
 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479
 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479 0.01270479
 0.01270479 0.01270479]
```

#### Current Version:
v2.20.0

**Comment by jgabry** [comment]
This is really the kind of question we prefer answering on the Stan Forums (https://discourse.mc-stan.org/ for next time), but the short answer is the default is a (potentially improper) uniform prior over the support. In this case that’s the whole real line for alpha and beta and just the positive part for sigma due to the constraint in the parameters block. The estimates you get of the parameters will depend heavily on the data, so it’s not possible to tell just from the priors what the posterior will look like. 

I’m going to close this since it’s not a feature request or formal bug report but happy to continue this discussion on the forum if you have follow up questions.
