### ISSUE TITLE
Size behavior is not consistent for function arguments

### ISSUE THREAD

**Issue by knkumar** [stan-dev/stan#2909]
#### Summary:
Size of a vector behaves differently from num_elements for function argument. 

#### Description:
The variable used for size function is a function argument, declared as a vector.
Size of a vector returns error during compilation but num_elements does not.

#### Reproducible Steps:
The current calculation I am working with uses a function with vector type argument.
The size of this vector argument is used for further calculations. 
num_elements seems to work fine but size fails.

If you have a reproducible example, please include it.
```
functions {

  real test(vector x){
    real N = size(x);
    return(N)
  }
}
```
#### Current Output:
The current output. Knowing what is the current behavior is useful.

```
SYNTAX ERROR, MESSAGE(S) FROM PARSER:
No matches for: 

  size(vector)

Available argument signatures for size:

  size(int[ ])
  size(real[ ])
  size(vector[ ])
  size(row_vector[ ])
  size(matrix[ ])
  size(int[ , ])
  size(real[ , ])
  size(vector[ , ])
  size(row_vector[ , ])
  size(matrix[ , ])
  size(int[ , , ])
  size(real[ , , ])
  size(vector[ , , ])
  size(row_vector[ , , ])
  size(matrix[ , , ])
  size(int[ , , , ])
  size(real[ , , , ])
  size(vector[ , , , ])
  size(row_vector[ , , , ])
  size(matrix[ , , , ])
  size(int[ , , , , ])
  size(real[ , , , , ])
  size(vector[ , , , , ])
  size(row_vector[ , , , , ])
  size(matrix[ , , , , ])
  size(int[ , , , , , ])
  size(real[ , , , , , ])
  size(vector[ , , , , , ])
  size(row_vector[ , , , , , ])
  size(matrix[ , , , , , ])
  size(int[ , , , , , , ])
  size(real[ , , , , , , ])
  size(vector[ , , , , , , ])
  size(row_vector[ , , , , , , ])
  size(matrix[ , , , , , , ])

 error in 'model42374ed5bbb7_model_code' at line 5, column 20
  -------------------------------------------------
     3: 
     4:   real test(vector x){
     5:     real N = size(x);
                           ^
     6:     return(N)
  -------------------------------------------------

Error in stanc(model_code = model_code) : 
  failed to parse Stan model 'model_code' due to the above error.
> 

```

#### Expected Output:
No error should be generated, could match to size(vector[ ])

#### Additional Information:
Provide any additional information here.

#### Current Version:
v2.22.0

**Comment by rok-cesnovar** [comment]
I am guessing you are using rstan which is still using the old Stan-to-C++ compiler.
The latest version of the compiler also supports the following:
```
int size(int)
int size(real)
int size(vector)
int size(row_vector)
int size(matrix)
```
This is available in the new compiler, which is currently only available through cmdstan and the cmdstanX interfaces and will 
be available in rstan in a future release. So this issue was already solved and I am going to close it.

**Comment by bob-carpenter** [comment]
Thanks for submitting a feature request.

The most general proposal would be to extend `size()` to arbitrary Stan types so that:

```
size(x)  = 1 if x:int or x:double

size(x) = 2 if x:complex

size(x) = rows(x) if x:vector

size(x) = cols(x) if x:row_vector

size(x) = rows(x) * cols(x) if x:matrix

size(x) = SUM_{n in 1:size(x)} size(x[n]) if x:T[]
```

We don't have complex types in the language, but should implement this function appropriately in the math library anyway.  

The math library implementation will be needed before this can be exposed to the stanc3 parser, so I'm going to move this to the math library as a feature request.  This shouldn't actually require any work in the `stan` repo.
