### ISSUE TITLE
Make integrators non-virtual with static methods

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stan#3041]
#### Summary:

Looking at the [integrators](https://github.com/stan-dev/stan/tree/develop/src/stan/mcmc/hmc/integrators) they actually don't have any member objects besides [`impl_leapfrog`](https://github.com/stan-dev/stan/blob/develop/src/stan/mcmc/hmc/integrators/impl_leapfrog.hpp) whose parameters  could be known at compile time.  What we could do is make all these methods static and have the calls in the hmc algorithms change from 

```cpp
      this->integrator_.evolve(this->z_, this->hamiltonian_, this->nom_epsilon_,
                               logger);
```

to 

```cpp
Integrator::evolve(this->z_, this->hamiltonian_, this->nom_epsilon_,
                               logger);
```

I like this for a couple reasons

1. Right now the integrators all do inheritance and virtual methods, but looking at those it seems like that is only because of the `Hamiltonian` being a template parameter on the class. But I don't see anywhere that the hamiltonian is used besides it's type being used in the method's defined in the integrators. tmk, virtual methods are really for when you want to use a pointer to a base class and then pass in and call classes that inherit from the base class. But looking around it seems everywhere we use an integrator we do know which one we are using so I don't really see a reason these are virtual

2. None of the `evolve()` methods use internal objects in the class, so I think they can just be `static` to signal that to the reader

3. There _might_ be some small speed gains from doing this, but personally I think this is nice because it's more obvious to the reader that there's nothing happening internally to the integrator here, it's just a static function so it's more like an interface than anything. 

#### Description:

We can rewrite the integrator classes like 

```cpp
// Note, no hamiltonian template parameter
class expl_leapfrog {
 public:
  template <typename Hamiltonian, typename, typename PointType>
  static void begin_update_p(PointType& z,
                      Hamiltonian& hamiltonian, double epsilon,
                      callbacks::logger& logger) {
    z.p -= epsilon * hamiltonian.dphi_dq(z, logger);
  }
//... other update
```

Then in the hmc class we can just call the static version of evolve like [here](https://github.com/stan-dev/stan/blob/develop/src/stan/mcmc/hmc/base_hmc.hpp#L114) with

```cpp
Integrator::evolve(this->z_, this->hamiltonian_, this->nom_epsilon_,
                               logger);
```

This is nice just because it makes things a little easier for the compiler at the call site. Though if we do still want to store an actual object in the hmc class then we can still do `integrator_::evolve();`

The main thing here is that none of the integrators hold anything that cannot be known at compile time. Are there types of integrators we would use where the integrator itself would have to store some state or hold memory when calling `evolve()`? If so then we should not do this. But otherwise it seems like it would be nice

#### Current Version:
v2.26.1

**Comment by betanalpha** [comment]
You have to keep in mind that the integrator and Hamiltonian code was designed at a time when we thought that we might have to expose lots of different integrators and Hamiltonians with different needs.  In particular there are more complex symplectic integrators that hold internal state that wouldn’t necessarily be known at compile time (for example higher-order integrators introduce new configuration parameters).  Like the implicit leapfrog integrator configuration parameters these could in principle be tuned dynamically, which would require non-static classes.  
We haven’t delved into those depths, however, and since the original modular design we’ve developed strong theoretical reasons why the first-order explicit leapfrog should be largely sufficient for most Hamiltonian Monte Carlo purposes.

In other words 

- Currently we don’t modify the internal state of any of the integrators.  
- Modifying the integrator state could be useful, but there aren’t immediate implementations

The original design was set up to be as flexible was possible, hence erring on the side of possibility.  Given what we know now about Hamiltonian Monte Carlo and symplectic integration there could be motivation for restricting the design, but that’s a deeper conversation.

> 	• Right now the integrators all do inheritance and virtual methods, but looking at those it seems like that is only because of the Hamiltonian being a template parameter on the class. But I don't see anywhere that the hamiltonian is used besides it's type being used in the method's defined in the integrators. tmk, virtual methods are really for when you want to use a pointer to a base class and then pass in and call classes that inherit from the base class. But looking around it seems everywhere we use an integrator we do know which one we are using so I don't really see a reason these are virtual
> 
The virtual classes here are being used to define an interface; see for example https://www.tutorialspoint.com/cplusplus/cpp_interfaces.htm. 

> 	• None of the evolve() methods use internal objects in the class, so I think they can just be static to signal that to the reader

Not directly, but they call the `update_p` and `update_q` methods which do use the internal state, at least for the implicit integrator.

> template <typename Hamiltonian, typename, typename
>  PointType>
>   
> static void begin_update_p
> (PointType& z,
>                       Hamiltonian& hamiltonian, 
> double
>  epsilon,
>                       callbacks::logger& logger) {
>     z.
> p -= epsilon * hamiltonian.dphi_dq
> (z, logger);
>   }

`PointType` isn’t independent from `Hamiltonian` — it’s defined by the template metaprogram `Hamiltonian::PointType`.

**Comment by SteveBronder** [comment]
icic if there are still possibilities then let's not do this. If I change my mind I'll come back to this but for now I think I was wrong when writing this and would rather keep the flexibility

**Comment by betanalpha** [comment]
To be honest I'm not that optimistic about the possibilities, but the cost of having the flexibility (and allowing people to fork and test different integrators) isn't that high either.

**Comment by SteveBronder** [comment]
Yeah I'm iffy as well but it seems like there are some people with interest in this space lately so lets leave this as is for now.
