### ISSUE TITLE
new vector slicing bound checks break code

### ISSUE THREAD

**Issue by chvandorp** [stan-dev/stan#3076]
#### Summary:
This issue results from a discussion on the Stan forum (https://discourse.mc-stan.org/t/new-slicing-rules-break-my-code/24985). Here I showed an example model that worked with Stan versions < 2.26, but resulted in thrown exceptions in newer versions. 

#### Description:
The issue is that the bounds `a` and `b` in an expression like `x[a:b]` now have to be valid indices (i.e. `0 < a, b <= n` where `n = num_elements(x)`. The previous behavior was that an expression like `x[1:0]` resulted in an empty vector. Below I'll give two examples in which this can be very useful. However, with the newer versions, this leads to a runtime error. These range checks are currently done for vectors, but not for arrays.

#### Reproducible Steps:
**Model 1:** inserting a constant into a parameter vector. This example comes from a model in which I modeled odds ratios `x` for different classes 1,2,...,n. The "user" of the model can choose a reference class `i`, and for this class the odds ratio will be 1. I then used the `transformed parameters` block to define a vector y = [x[1], x[2], ..., x[i-1], 1, x[i], ..., x[n-1]]. (note that the vector `x` has length `n-1`). I implemented this as follows:
```stan
data {
    int<lower=1> n; // length of vector y
    int<lower=1, upper=n> i; // index of reference class
}
parameters { 
    vector[n-1] x; // odds ratios of other classes
}
transformed parameters {
    vector[n] y = append_row(x[:i-1], append_row(rep_vector(1.0, 1), x[i:]));
}
model {
    y ~ normal(0, 1); // do something with y
}
```
Whenever `i > 1` and `i < n` there is no problem with this, but when the user chooses `i=1`, then the first slice `x[:i-1]` is equal to `x[:0]`, which used to represent an empty vector. Currently, we get an exception, because 0 is not a valid index. We get a similar situation with `i=n`. (BTW: I'm aware that my model can be fixed using `head` and `tail` functions :-).

**Model 2**: ragged data/parameter structure.  
Suppose that we have `N` subjects and for each subject we have a number of observations, some of which may be missing. The number of missing observations `K[n]` differs between subjects and crucially **can be zero** for some subjects. We want to model these missing observations explicitly using a vector `vector[sum(K)] x`. The missing observations specific for subject `n` can be selected from `x` using `vector[K[n]] y = x[sum(K[:n-1])+1:sum(K[:n])]`. Here's a "working" Stan model:
```stan
data {
    int N; // number of subjects
    int<lower=0> K[N]; // number of missing observations for each subject
}
parameters {
    vector[sum(K)] x; // concatenated missing observations
}
model {
    for ( n in 1:N ) {
        // get the part of x corresponding to subject n        
        vector[K[n]] y = x[sum(K[:n-1])+1:sum(K[:n])];

        // do something with y...
    }
    x ~ normal(0,1);
}
```
This model works without errors when e.g. `K = {1,5,3,0,4}` (note that subject 4 has zero missing observations), but we get exceptions when e.g. `K = {0,1,5,3,4}`, because in that case we select `vector[0] y = x[1:0]` for the first subject. Something similar happens for when `K[N] = 0`.

#### Current Output:
The error is a thrown exception like this one:
```
vector[min] indexing: accessing element out of range. index 4 out of range; expecting index to be between 1 and 3
```

#### Expected Output:
The models work without warnings or exceptions with Stan versions < 2.26

#### Additional Information:
* There was some discussion on the forum whether or not the old behavior was actually unintended and a "bug" instead of a feature. Intended or not, I think it is pretty useful and also common practice in other languages (e.g. Python, Julia, Go).
* Others argued that allowing out-of-range indices could lead to uncaught programming errors.
* The change was likely made here: https://github.com/stan-dev/stan/pull/2965
* For arrays, this kind of slicing is still allowed: if we replace all `x` and `y` by `array`s, all models work without errors in the current version. So this is somewhat inconsistent.

For now, I would argue that the change has to be reverted, because it could break a lot of people's models (I can't be the only one making use of this). Then we can have a discussion about returning empty vectors or throwing exceptions.

#### Current Version:
v2.28.1

**Comment by fcostin** [comment]
(i'm `rfc` from the Stan forum thread(https://discourse.mc-stan.org/t/new-slicing-rules-break-my-code/24985))

I was at first confused about when a slice should throw an error vs evaluate to a (perhaps empty) array of indices. 

When defining the behaviour for`x[start:end]` there are two options: 
(i) we could first check to see if `start` and `end` are both valid indices with respect to the shape of `x`, throw an error if not, and otherwise expand `start:end` to a (possibly empty) array of indices.
(ii) we could first expand `start:end` to a (possibly empty) array of indices first, and then -- provided that produces a nonempty range of indices -- check to see if all those are valid with respect to the shape of `x`, and throw an error otherwise.

An interesting example is the case where `x` has size 1 -- how can we write an empty slice of the form `x[start:end]` in this case?  Since Stan's slices are inclusive of both `start` and `end` indices, if the desired behaviour is that `start>end` represents an empty slice, then as `x` has size 1, at least one value out of `start` and `end` must be an invalid index, since the set of possible valid indices for `x` only contains the index 1.  This suggests that option (i) above, checking the validity of indices with respect to the size of `x` before expanding them to a range of indices, is not compatible with being able to select empty slices of arbitrary sized arrays.

Similarly for the case where `x` has size 0.

@bob-carpenter 's intended semantics seem consistent with option (ii) and would support both of these scenarios.

It might also be worth double-checking that the semantics for `[start:end]` slices work in a consistent way to `start:end` syntax in for loops  https://mc-stan.org/docs/2_28/reference-manual/for-loops.html#for-loops

**Comment by chvandorp** [comment]
@fcostin In a for loop, `start:end` is empty when `start > end`.

@SteveBronder if you want to keep the reverse order functionality, you could propose an additional stride parameter, as in MATLAB or Julia: `3:-1:1` would represent the sequence 3,2,1. Eigen also support a (negative) stride, I believe.

**Comment by bob-carpenter** [comment]
@fcostin:  In general, if `x` is an array, then `x[1:size(x)]` is equivalent to `x`.  If `x` is size 0, then `x[1:0] = {}`.  If `x` is size 1, then `x[1:1] = { x[1] }`, and so on.

My intended semantics was that `start:end = { start, start + 1, ..., end }`.   Then the boundary condition if `start > end` is that `start:end = { }`.
