### ISSUE TITLE
matrix assignment with inconsistent size

### ISSUE THREAD

**Issue by yizhang-yiz** [stan-dev/stan#3084]
#### Summary:
I just realized I can do assignment to a matrix of different size in `transformed param` block. I'm actually not sure if this is by design.

#### Description:
See below.

#### Reproducible Steps:
Using 2.28.1, I can do this
```stan
transformed parameters {
  matrix[2,2] x = [[-4.6, 0.0], [0.0,-2.8]];
  matrix[1,1] y = x;
  print(y[1,1], " ", y[2,2]);
}
```
The output is 
```bash
//....
Model contains no parameters, running fixed_param sampler, no updates to Markov chain
-4.6 -2.8

-4.6 -2.8
//...
```
Doing the same in `transformed data` block causes runtime error, as I expect
```stan
transformed data {
  matrix[2,2] x = [[-4.6, 0.0], [0.0,-2.8]];
  matrix[1,1] y = x;
  print(y[1,1], " ", y[2,2]);
}
```
The output:
```bash
Assertion failed: (rows == this->rows() && cols == this->cols() && "DenseBase::resize() does not actually allow to resize."), function resize, file stan/lib/stan_math/lib/eigen_3.3.9/Eigen/src/Core/DenseBase.h, line 257.
```

#### Expected Output:
Assertion failure error.

#### Current Version:
v2.28.1

**Comment by rok-cesnovar** [comment]
This has been a long standing issue. There is an issue open in stanc3 for it: https://github.com/stan-dev/stanc3/issues/523 but we have since established its not the fault of stanc3. I believe there is only a check missing in https://github.com/stan-dev/stan/blob/develop/src/stan/model/indexing/assign.hpp

I think no one wants to touch this one because there is a never confirmed (I think it was even denied on multiple occasions) that this bug is abused somewhere in rstanarm.

**Comment by bob-carpenter** [comment]
@bgoodri:  can you confirm exactly which piece of the error checking for sizes you need us not to fix (until we get ragged arrays)?

**Comment by WardBrian** [comment]
Ben seems to think it's not him using it: https://github.com/stan-dev/stanc3/issues/523#issuecomment-617462065

I think it wouldn't be too unreasonable to patch it in a branch and then test RStan, brms, and rstanarm against it now that we have the ability to use RStan on newer versions?

**Comment by bgoodri** [comment]
I doubt anyone is using that on purpose.
