### ISSUE TITLE
Is there a way to constrain the sum to 1 which the element is possible to be 0?

### ISSUE THREAD

**Issue by petergaoshan** [stan-dev/stan#3136]
For the simplex data type, the sum of vector is constrained to be 1. However, in the document it says all values are positive. Is there a way to have the same constraint but allows 0 to exist in the data?

**Comment by bob-carpenter** [comment]
Thanks for engaging, @petergaoshan.   Roughly speaking, we logit transform the simplex parameters and sample in the unconstrained space (details in the reference manual chapter on constraining transforms).  With that transform, simplex values of 1 and 0 map to + and - infinity in the unconstrained space, which destroys all of our numerics.  In practice, we get 0 or 1 values due to overflow or underflow of the exp() in the inverse transform, but those aren't practically usable because all the derivatives break and the algorithm fails (it will probably report divergence warnings).  And it's not just us---most algorithms run into problems at the boundaries of constrained spaces when performing inference.

The good news is that you probably don't want 0 or 1 values anyway.  With Bayesian posterior inference, if we parameterize a multinomial model with a simplex, zeros in the data do not correspond to zeros in the posterior simplex.   

I'm going to close this because it's not an issue for the software.   @petergaoshan --- if you'd like to continue this discussion, please ask general questions like this on the Stan forums:  https://discourse.mc-stan.org
