### ISSUE TITLE
Allow drawing from the Laplace approximation and Pathfinder without evaluating log_p

### ISSUE THREAD

**Issue by avehtari** [stan-dev/stan#3215]
#### Summary:

Currently, when drawing from the Laplace approximation, log_p and log_q are always evaluated for each draw. log_p and log_q are useful for diagnosing the accuracy of the Laplace approximation, but there are cases where we trust that the normal approximation at the mode is sufficient and then we would not need log_p and log_q, and evaluation of log_p for all draws usually takes much more time than finding the mode, computing hessian, and drawing from the normal take. So it would be useful to make it optional and output just 0 or NA to the csv when the user so requests.

The relevant part in Stan services is 
https://github.com/stan-dev/stan/blob/3c2b7bad93e37e787fd456e712996b19ef84de1f/src/stan/services/optimize/laplace_sample.hpp#L110

Naturally the change would need to make also in stan/arguments, cmdstan, and other interfaces, too

#### Current Version:
v2.32.2

**Comment by bob-carpenter** [comment]
I'm OK with providing this option.  Some notes:

* do we drop log_p and log_q both or provide independent options to drop either?
* I would strongly prefer to drop columns in the output rather than including dummy values to prevent people from trying to use it
* Our HMC sampler always provides log_p (and never provides log_q), so code that always assumes it exists will go astra
* log_q takes about the same amount of time as drawing a sample given that we have Cholesky factored already (i.e., it's a *high* cost)

**Comment by avehtari** [comment]
- For simplicity I would drop both
- I suggested dummy values as I assumed there can be code assuming their existence, but I'm fine dropping the columns, too

**Comment by SteveBronder** [comment]
Also adding Pathfinder for this to not evaluate `lp__` for the return samples for each pathfinder

**Comment by avehtari** [comment]
#3249 fixed this for Pathfinder, but I guess Laplace part is not yet done
