### ISSUE TITLE
Restore state from output file

### ISSUE THREAD

**Issue by betanalpha** [stan-dev/stan#355]
Stan output files currently have all the information needed to restore the configuration and state, allowing restarting of sampling/optimization or just saving a complex configuration instead of having to reenter from the command line.

The argument code has to be extended a bit but everything should be straightforward.

**Comment by JohannesBuchner** [comment]
I wanted to request this feature too. It seems natural to first run optimization to a likelihood uncertainty of ~+-10, and then start MCMC or VB there -- especially if one knows that there is only one maximum.
Currently init= can not read what output file=out.csv has written. 

An alternative would be to provide a tool that converts from csv to Rdata format, which has to handle arrays/vectors/matrices correctly.

**Comment by bob-carpenter** [comment]
We'll make that possible, but it's not something we'd generally
recommend.  And yes, I know PyMC does it and others recommend
it regularly.

It can work with simple models, but in those cases it's not
necessary.  For models like hierarchical
regressions, there aren't even optima --- the total joint probability
(log likelihood + log prior) is unbounded.  In high dimensions, the
posterior mode is often very far away from the high mass region of the
posterior.  Also, VB converges about as fast as optimization, so no
reason to run optimization first.

So what people often do is run a couple steps of optimization,
because getting near the posterior mode is often a bad state to
start MCMC from (it can be hard to escape and find the high posterior
mass given the algorithms we use).

Of course, future research may figure out a good way to use this.

- Bob

**Comment by JohannesBuchner** [comment]
Well, I can not make claims about the general case, but my specific problem, which is a ~100 dimensional hierarchical model (but with intermediate priors) with a single, well-behaved posterior maximum (gaussian, with correlations) at the ML, would definitely benefit from it (reducing the number of Metropolis steps until reaching the maximum from 500 to 200, with each likelihood evaluation taking 1s). The main motivation is, however, that I can always start from that maximum and experiment with different priors.

In the meantime, I wrote a script that does the job; you can find it as csv2Rdata.py in https://github.com/JohannesBuchner/ic4stan

**Comment by bob-carpenter** [comment]
Thanks for the comments.  We don't need more convincing, by the
way --- this feature's going in for all sorts of reasons.  It
should be available in Stan 3 (no target date yet, but it certainly
won't be in the next few months).

What's the form of the hierarchical model that has an MLE?  
Standard ones are degenerate around hierarchical variance = 0
solutions.  

I'm not sure what sampler you're using --- NUTS doesn't have
a Metropolis step --- it uses slice sampling along the Hamiltonian
trajectory.  Basic HMC does have a Metropolis accept/reject step.
So I'm guessing you're saying it takes 500 iterations to settle
into stationary behavior (i.e., converge).

In very many cases, the MLE is not a good place to start, either
because it's far away from the high-mass region of the posterior
or simply doesn't exist.  So we can't make this kind of behavior
the default.  And it can be very very hard to get the sampler
away from the MLE in some cases where it's not near the high
mass region.

One place people use this kind of thing is in path sampling, which
sounds like what you're talking about.  You start with a prior
of a given strength, fit it, then run again with a closely related
prior, using a "warm start" from the previous solution.  Then you
do this for a whole sequence of priors (the "path" in this case).  
This is usually used in penalized MLE approaches --- Hastie et
al. discuss it in their machine learning book and papers, like
their one on the elastic net.

- Bob

**Comment by JohannesBuchner** [comment]
Ah, yes I meant iterations, I was thinking of HMC. You can find the gory details in the Appendix of http://adsabs.harvard.edu/abs/2015ApJ...802...89B, including Stan code. In brief, I first obtain posterior samples for the lower levels with intermediate priors using nested sampling (2000 objects which each provide a 5d problem with multiple solutions), then use Stan for the higher-level to replace those priors with a population density, and do the lower-level integrations explicitly with the re-weighted posterior samples. So for Stan it is not the kind of hierarchical model you are thinking of.

**Comment by JohannesBuchner** [comment]
I use NUTS.

**Comment by bob-carpenter** [comment]
Thanks for the clarification.  If you want feedback on the model,
you'll need to grab Michael's attention (or maybe Andrew --- he was
a physics undergrad several decades back).

We'll definitely be implementing this functionality in Stan 3.
No projected date for that yet, so it's not going to help you out
any time soon.

- Bob

**Comment by bob-carpenter** [comment]
will be a side effect of #1706 where it's not CmdStan specific
