### ISSUE TITLE
Compare Ensemble Samplers to HMC

### ISSUE THREAD

**Issue by PeterLi2016** [stan-dev/stan#774]
I talked to Bob about comparing the ensemble samplers that are in https://github.com/stan-dev/stan/tree/feature/issue-362-ensemble-samplers to HMC but we're not sure what models to use for comparison. We want to use a selection of models that are fairly representative. Any suggestions?

**Comment by betanalpha** [comment]
After working some sweet, sweet template magic the refactor
compile time is on par with the develop compile time (both just
under 12 seconds for a simple model with very little autodiff
to compile).  BUT we can do better.

Right now there�s a nontrivial hit from having to pass a Writer
through all of the samplers.  But the Writer is used only once,
when a Hamiltonian class tries to compute a gradient and
spits out the �about to be rejected� error message on failure.
In particular, the Hamiltonian class wraps the gradient call
in a try/catch block, and if it catches an exception then it
sets the potential to infinity (which will allow the sampler
to gracefully terminate) and spits out the error message.

In order to avoid a Writer template we�d have to either
pass the writer through each call (sample -> transition ->
evolve -> components of the leapfrog update -> gradient)
or not catch the exception internally (in which case the 
sampler won�t be able to fail as gracefully).  Both seem
ugly and unhappy.

Anyone have any suggestions on how to sneak an error
message out from deep in the code without having an
internal reference to a Writer implementation?  I dunno,
like storing an error string and calling write_error_message
after each transition or something?

**Comment by bob-carpenter** [comment]
One thing to do is wrap all the components that 
need to get plumbed into the depths into a struct so
the passing isn't so onerous.

I take it it's not possible just have the Hamiltonian
class throw an exception that's caught above?

- Bob

**Comment by betanalpha** [comment]
> One thing to do is wrap all the components that 
> need to get plumbed into the depths into a struct so
> the passing isn't so onerous.

It�s just one object that needs to be passed, it just
needs to be passed through a ton of functions since
the log_prob call is deep inside of all the MCMC code
relative to the transition method.

> I take it it's not possible just have the Hamiltonian
> class throw an exception that's caught above?

The problem is that would mess up the current way
the MCMC code fails gracefully.  I think it would be
possible to play hot potato with the exceptions but it
would require a nontrivial rewrite of the MCMC code.

**Comment by bob-carpenter** [comment]
Isn't this commentary on the wrong issue?

And for some reason, it looks like your character encoding is
being messed up.

I don't understand the details, but shouldn't throwing an
exception have the same behavior as setting the log prob
to -inf?

- Bob

**Comment by bob-carpenter** [comment]
Rolled into #362
